insert into mapa
(nome)
values ('Mapa Padrão');

insert into estado
(idMapa, nome, sigla, descricao)
values
(1, 'Ambarino', 'AM', 'Ambarino é um dos cinco estados americanos em Red Dead Redemption 2. É o estado mais elevado.Lute contra os elementos e encontre as montanhas de frente na vasta e acidentada paisagem de Ambarino.Viaje pela neve, veja geleiras e gêiseres poderosos, ursos de caça que vagam pelos Grizzlies ou apreciam as águas azuis do ravino de Calumet.O estado de Ambarino está localizado na parte norte do mapa em Red Dead Redemption 2. É dividido em duas regiões: Grizzlies East e Grizzlies West.Abaixo, você encontra a lista de animais, cavalos, armas, personagens e gangues que você pode encontrar no Red Dead Redemption 2 no estado de Ambarino, bem como as missões que ocorrem no território, fotos, vídeos e muito mais.Vida selvagem: urso marrom norte -americano (Grizzly)'),
(1, 'Lemoyne', 'LE', 'Lemoyne é um dos cinco estados americanos em Red Dead Redemption 2. Aproveite os prados exuberantes e o clima do sul do campo de Lemoyne, ou aprecie as luzes da cidade cultural de São Denis.Isso é se você passar pelo pântano agourento e Bayou NWA.O estado de Lemoyne está localizado na parte sudeste do mapa em Red Dead Redemption 2. É dividido em três regiões: Scarlett Meadows, Bayou Nwa e Bluewater Marsh.Abaixo, você encontra a lista de animais, cavalos, armas, personagens e gangues que você pode encontrar no Red Dead Redemption 2 no estado de Lemoyne, bem como as missões que ocorrem no território, fotos, vídeos e muito mais.'),
(1, 'New Austin', 'NA', 'New Austin é um dos cinco estados americanos em Red Dead Redemption 2. Experimente o calor do deserto implacável de Austin em uma paisagem de rocha vermelha e sol alto.Somente os viajantes mais difíceis sobrevivem ao deserto árido.Então esfrie nos riachos e na terra de pastagem do lugar de Hennigan.O estado de New Austin está localizado na parte sudoeste do mapa em Red Dead Redemption 2. É dividido em quatro regiões: Cholla Springs, Gaptooth Ridge, Hennigan''s Stead e Rio Bravo.No modo de história de Red Dead Redemption 2, New Austin não pode ser acessado até o epílogo.Abaixo, você encontra a lista de animais, cavalos, armas, personagens e gangues que você pode encontrar no Red Dead Redemption 2 no estado de New Austin, bem como as missões que ocorrem no território, fotos, vídeos e muito mais.'),
(1, 'New Hanover', 'NH', 'New Hanover é um dos cinco estados americanos em Red Dead Redemption 2. É o maior território do jogo.O estado diverso de New Hanover é uma terra de planícies e florestas extensas, perfeitas para caçadores e herbalistas.Fora das cidades e campos de petróleo da mineração, a natureza inexplorada espera.O estado de New Hanover está localizado na parte leste do mapa em Red Dead Redemption 2. É dividido em três regiões: os Heartlands, Cumberland Forest e Roanoke Ridge.Abaixo, você encontra a lista de animais, cavalos, armas, personagens e gangues que você pode encontrar no Red Dead Redemption 2 no estado de New Hanover, bem como as missões que ocorrem no território, fotos, vídeos e muito mais.'),
(1, 'West Elizabeth', 'WE', 'West Elizabeth é um dos cinco estados americanos em Red Dead Redemption 2. Se você está caçando bisonte nas grandes planícies, apreciando as vistas de Big Valley ou enfrentando a região sinistra de árvores altas, o oeste de Elizabeth é rico e cheio deoportunidade.O estado de West Elizabeth está localizado na parte oeste do mapa em Red Dead Redemption 2. É dividido em três regiões: árvores altas, grandes planícies e Big Valley.Abaixo, você encontra a lista de animais, cavalos, armas, personagens e gangues que você pode encontrar no Red Dead Redemption 2 no estado de West Elizabeth, bem como as missões que ocorrem no território, fotos, vídeos e muito mais.'),
(1, 'Guarma', 'GA', 'Guarma é uma ilha tropical apresentada em Red Dead Redemption 2. Este é um local especial que não faz parte do mapa principal do jogo, pois é acessado apenas durante o capítulo 5 do modo de história.Guarma é uma ilha de plantação de cana -de -açúcar e é descrita como a segunda ilha a leste de Cuba.É o lar de espécies de aves exóticas e outros animais que podem ser encontrados exclusivamente no Guarma.A ilha é dominada pelo coronel Fussar, um tirano local, mantido no poder pelas empresas de açúcar.O Guarma normalmente pode ser acessado apenas durante o capítulo 5 da história do RDR2.No entanto, é possível alcançá -lo a qualquer momento usando uma falha (consulte o vídeo abaixo).Abaixo, você encontra a lista de animais e personagens que você pode encontrar na ilha de Guarma, bem como as missões que ocorrem no território, fotos, vídeos e muito mais.');

insert into estado_faz_fronteira_com_estado
(siglaEstadoOrigem, siglaEstadoFronteira)
values
('AM', 'NH'),
('AM', 'WE'),
('NH', 'WE'),
('NH', 'LE'),
('WE', 'NA'),
('NH', 'AM'),
('WE', 'AM'),
('WE', 'NH'),
('LE', 'NH'),
('NA', 'WE');

insert into cidade
(nome, siglaEstado, descricao)
values
('Annesburg', 'NH', 'A vida não é fácil para os mineiros e suas famílias em Annesburg, que fornecem carvão para o rio Lannahechee há quase um século.As condições de trabalho são terríveis para pouco salário, e muitos homens perderam a vida no poço.'),
('Armadillo', 'NA', 'Armadillo é um assentamento encontrado no mundo de Red Dead Redemption e Red Dead Redemption 2. Está localizado na região de Cholla Springs do novo território de Austin.Armadillo sofria de muitos surtos de doenças.A cidade é descrita como sendo uma "cidade fantasma" e os viajantes são dissuadidos de visitar.A cidade recebeu o nome do animal do tatu, que também é encontrado no jogo.'),
('Blackwater', 'WE', 'Blackwater é um local apresentado no mundo da redenção de Red Dead e na Red Dead Redemption 2. Está localizado na região de Great Plains, no território de West Elizabeth.Blackwater e sua área circundante foram colocados em bloqueio pelos Pinkertons, seguindo o assalto executado pela gangue van der Linde que resultou em um enorme tiroteio entre as duas facções (antes dos eventos de Red Dead Redemption 2).'),
('Colter', 'AM', 'Colter é um assentamento encontrado no mundo de Red Dead Redemption 2. Está localizado na região oeste do Grizzlies, do território de Ambarino.Serve como a localização do acampamento durante o primeiro capítulo do jogo.Em breve.'),
('Lagras', 'LE', 'Um pequeno assentamento remoto nos pântanos de Bayou Nwa, LeMoyne, o povo de Lagras ao vivo auto-suficientemente suficientemente suficientes, ganhando um pouco de dinheiro aqui e ali, de pescar e agir como guias para os viajantes que desejam navegar pela região.Em breve.'),
('Mount Hagen', 'AM', 'Um dos picos mais conhecidos nos Grizzlies nevados de Ambarino, Mount Hagen Torres acima do lago Isabella, a oeste e o Beartooth Beck, a leste, que fornece o passe principal pela cordilheira ocidental e se junta ao rio Dakota mais ao sul.'),
('Rhodes', 'LE', 'Prime e adequado na superfície, tensões e corrupção correm profundamente na cidade de Rhodes, que durante anos foi pego no fogo cruzado entre os Braithwaites e os Grays, duas famílias de plantação em guerra.'),
('Saint Denis', 'LE', 'Uma porta -chave para a América do Norte com uma rota comercial que percorre toda a extensão do país, a movimentada cidade de São Denis é um caldeirão de culturas e pessoas onde homens, socialites, marinheiros, trabalhadores, mendigos e ladrões vivem lado a lado.'),
('Strawberry', 'WE', 'O Strawberry era pouco mais que uma pequena cidade de madeireira até a chegada de seu novo prefeito, um excêntrico da costa leste, que é obcecado em transformá -lo em um farol cultural para turistas ricos, para grande parte dos moradores dos habitantes locais.Em breve.'),
('Tumbleweed', 'NA', 'Tumbleweed é um assentamento encontrado no mundo de Red Dead Redemption e Red Dead Redemption 2. Está localizado na região de Gaptooth Ridge do novo território de Austin.A cidade é assediada pela gangue Del Lobos.Em breve.'),
('Valentine', 'NH', 'Uma cidade estridente e desgastada no Heartlands, os leilões de gado dos namorados atraem comerciantes, fazendeiros, cowboys, jogadores, bandidos e prostitutas de toda a parte, todos querendo ganhar dinheiro, levantar um pouco e se divertir.');

-- Assumindo IDs: 
-- Annesburg = 1, Armadillo = 2, Blackwater = 3, Colter = 4, Lagras = 5, 
-- Mount Hagen = 6, Rhodes = 7, Saint Denis = 8, Strawberry = 9, Tumbleweed = 10, Valentine = 11
insert into cidade_conecta_com_cidade
(idCidadeOrigem, idCidadeDestino)
values
(1, 11),  -- Annesburg conecta com Valentine (ambas estão em New Hanover)
(2, 10),  -- Armadillo conecta com Tumbleweed (ambas estão em New Austin)
(3, 9),   -- Blackwater conecta com Strawberry (ambas estão em West Elizabeth)
(4, 6),   -- Colter conecta com Mount Hagen (ambas estão em Ambarino)
(5, 8),   -- Lagras conecta com Saint Denis (ambas estão em Lemoyne)
(7, 8),   -- Rhodes conecta com Saint Denis (ambas estão em Lemoyne)
(9, 3),   -- Strawberry conecta com Blackwater (ambas estão em West Elizabeth)
(11, 7),  -- Valentine conecta com Rhodes (NH com LE)
(11, 1),  -- Valentine conecta com Annesburg
(10, 2),  -- Tumbleweed conecta com Armadillo
(9, 3),   -- Strawberry conecta com Blackwater
(6, 4),   -- Mount Hagen conecta com Colter
(8, 5),   -- Saint Denis conecta com Lagras
(8, 7),   -- Saint Denis conecta com Rhodes
(3, 9),   -- Blackwater conecta com Strawberry
(7, 11);  -- Rhodes conecta com Valentine

insert into estabelecimento
(nome, descricao)
values
('Salão', 'Local para beber, jogar e, às vezes, iniciar uma briga.'),
('Loja de Variedades', 'Vendendo uma ampla gama de mercadorias, incluindo alimentos, munição e roupas.'),
('Loja de Armas', 'Vendendo armas, munição e serviços de personalização de armas.'),
('Barbeiro', 'Oferece cortes de cabelo e serviços de barbear.'),
('Médico', 'Vendendo suprimentos médicos e tônicos.'),
('Hotel', 'Fornece hospedagem e um lugar para trocar de roupa ou tomar um banho.'),
('Estação de Trem', 'Serve como ponto de viagem rápida e local para enviar/receber correspondências ou pacotes.'),
('Agência dos Correios', 'Onde os jogadores podem coletar ou enviar correspondências e pagar recompensas.'),
('Banco', 'Local seguro para armazenar valores ou roubar.'),
('Açougue', 'Onde os jogadores podem vender carcaças de animais e carne.'),
('Alfaiate', 'Vendendo roupas e trajes.'),
('Estábulo', 'Local para comprar, vender ou cuidar de cavalos.'),
('Mercador de Contrabando', 'Compra e vende mercadorias roubadas, itens raros e armas especiais.'),
('Loja de Iscas', 'Vendendo iscas, anzóis e suprimentos de pesca.'),
('Acampamento', 'Local onde você pode descansar, fabricar e interagir com sua gangue.'),
('Igreja', 'Edifício religioso encontrado em algumas cidades.'),
('Cabana e Casa', 'Diversas casas e cabanas espalhadas pelo mundo, muitas vezes ligadas a missões secundárias ou segredos escondidos.'),
('Fábrica', 'Local industrial, frequentemente envolvido em missões da história.'),
('Pátio de Trem', 'Local associado ao transporte ferroviário e logística.'),
('Cidade e Vilarejo', 'Área geral com vários estabelecimentos e residentes.'),
('Delegacia do Xerife', 'Centro de aplicação da lei onde as recompensas são coletadas.'),
('Ferreiro', 'Encontrado em algumas cidades, tipicamente como parte da ambientação ou eventos da história.'),
('Plantação', 'Grande propriedade frequentemente ligada à narrativa do jogo.'),
('Acampamento de Fora da Lei', 'Acampamento de gangues rivais que pode ser atacado.'),
('Cemitério', 'Local de importância histórica ou narrativa.'),
('Cabine e Sítio', 'Residência remota, muitas vezes ligada a encontros aleatórios ou histórias secundárias.'),
('Corretor', 'Vendendo imóveis, como casas ou propriedades (relacionado ao modo história).');

insert into personagem_tipo
(idPersonagem, tipo)
values
(1, 'NPC'),
(2, 'NPC'),
(3, 'NPC'),
(4, 'NPC'),
(5, 'NPC'),
(6, 'NPC'),
(7, 'NPC'),
(8, 'NPC'),
(9, 'NPC'),
(10, 'NPC'),
(11, 'NPC'),
(12, 'NPC'),
(13, 'NPC'),
(14, 'NPC'),
(15, 'NPC'),
(16, 'NPC'),
(17, 'NPC'),
(18, 'NPC'),
(19, 'NPC'),
(20, 'NPC'),
(21, 'NPC'),
(22, 'NPC'),
(23, 'NPC'),
(24, 'NPC'),
(25, 'NPC'),
(26, 'NPC'),
(27, 'NPC'),
(28, 'NPC'),
(29, 'NPC'),
(30, 'NPC'),
(31, 'NPC'),
(32, 'NPC'),
(33, 'NPC'),
(34, 'NPC'),
(35, 'NPC'),
(36, 'NPC'),
(37, 'NPC'),
(38, 'NPC'),
(39, 'NPC'),
(40, 'NPC'),
(41, 'NPC'),
(42, 'NPC'),
(43, 'NPC'),
(44, 'NPC'),
(45, 'NPC'),
(46, 'NPC'),
(47, 'NPC'),
(48, 'NPC'),
(49, 'NPC'),
(50, 'NPC'),
(51, 'NPC'),
(52, 'NPC'),
(53, 'NPC'),
(54, 'NPC'),
(55, 'NPC'),
(56, 'NPC'),
(57, 'NPC'),
(58, 'NPC'),
(59, 'NPC'),
(60, 'NPC'),
(61, 'NPC'),
(62, 'NPC'),
(63, 'NPC'),
(64, 'NPC'),
(65, 'NPC'),
(66, 'NPC'),
(67, 'NPC'),
(68, 'NPC'),
(69, 'NPC'),
(70, 'NPC'),
(71, 'NPC'),
(72, 'NPC'),
(73, 'NPC'),
(74, 'NPC'),
(75, 'NPC'),
(76, 'NPC'),
(77, 'NPC'),
(78, 'NPC'),
(79, 'NPC'),
(80, 'NPC'),
(81, 'NPC'),
(82, 'NPC'),
(83, 'NPC'),
(84, 'NPC'),
(85, 'NPC'),
(86, 'NPC'),
(87, 'NPC'),
(88, 'NPC'),
(89, 'NPC'),
(90, 'NPC'),
(91, 'NPC'),
(92, 'NPC'),
(93, 'NPC'),
(94, 'NPC'),
(95, 'NPC'),
(96, 'NPC'),
(97, 'NPC'),
(98, 'NPC'),
(99, 'NPC'),
(100, 'NPC'),
(101, 'NPC'),
(102, 'NPC'),
(103, 'NPC'),
(104, 'NPC'),
(105, 'NPC'),
(106, 'NPC'),
(107, 'NPC'),
(108, 'NPC'),
(109, 'NPC'),
(110, 'NPC'),
(111, 'NPC'),
(112, 'NPC'),
(113, 'NPC'),
(114, 'NPC'),
(115, 'NPC'),
(116, 'NPC'),
(117, 'NPC'),
(118, 'NPC'),
(119, 'NPC'),
(120, 'NPC'),
(121, 'NPC'),
(122, 'NPC'),
(123, 'NPC'),
(124, 'NPC'),
(125, 'NPC'),
(126, 'NPC'),
(127, 'NPC'),
(128, 'NPC'),
(129, 'NPC'),
(130, 'NPC'),
(131, 'NPC'),
(132, 'NPC'),
(133, 'NPC'),
(134, 'NPC'),
(135, 'NPC'),
(136, 'NPC'),
(137, 'NPC'),
(138, 'NPC'),
(139, 'NPC'),
(140, 'NPC'),
(141, 'NPC'),
(142, 'NPC'),
(143, 'NPC'),
(144, 'NPC'),
(145, 'NPC'),
(146, 'NPC'),
(147, 'NPC'),
(148, 'NPC'),
(149, 'NPC'),
(150, 'NPC'),
(151, 'NPC'),
(152, 'NPC'),
(153, 'NPC'),
(154, 'NPC'),
(155, 'NPC'),
(156, 'NPC'),
(157, 'NPC'),
(158, 'NPC'),
(159, 'NPC'),
(160, 'NPC'),
(161, 'NPC'),
(162, 'NPC'),
(163, 'NPC'),
(164, 'NPC'),
(165, 'NPC'),
(166, 'NPC'),
(167, 'NPC'),
(168, 'NPC'),
(169, 'NPC'),
(170, 'NPC'),
(171, 'NPC'),
(172, 'NPC'),
(173, 'NPC'),
(174, 'NPC'),
(175, 'NPC'),
(176, 'NPC'),
(177, 'NPC'),
(178, 'NPC'),
(179, 'NPC'),
(180, 'NPC'),
(181, 'NPC'),
(182, 'NPC'),
(183, 'NPC'),
(184, 'NPC'),
(185, 'NPC'),
(186, 'NPC'),
(187, 'NPC'),
(188, 'NPC'),
(189, 'NPC'),
(190, 'NPC'),
(191, 'NPC'),
(192, 'NPC'),
(193, 'NPC');

insert into inventario
(totalItens, capacidade)
values
();

insert into classe
(nome),
values
();

insert into historia
(titulo, enredo)
values
();

insert into missao
(titulo, nivelDificuldade, idHistoria, idEstado)
values
();

insert into missao_depende_de_missao
(idMissaoAtual, idMissaoAnterior)
values
();

-- insert into jogador

insert into npc
(idPersonagem, nome, velocidade, vidaMax, staminaMax)
values
(1, 'Abigail Roberts (Marston)', 7, 100, 1000),
(2, 'Arthur Morgan', 7, 100, 1000),
(3, 'Bill Williamson', 7, 100, 1000),
(4, 'Charles Smith', 7, 100, 1000),
(5, 'Dutch Van Der Linde', 7, 100, 1000),
(6, 'Hosea Matthews', 7, 100, 1000),
(7, 'Jack Marston', 7, 100, 1000),
(8, 'Javier Escuella', 7, 100, 1000),
(9, 'John Marston', 7, 100, 1000),
(10, 'Josiah Trelawny', 7, 100, 1000),
(11, 'Karen Jones', 7, 100, 1000),
(12, 'Kieran Duffy', 7, 100, 1000),
(13, 'Lenny Summers', 7, 100, 1000),
(14, 'Leopold Strauss', 7, 100, 1000),
(15, 'Mary-Beth Gaskill', 7, 100, 1000),
(16, 'Micah Bell', 7, 100, 1000),
(17, 'Molly O''Shea', 7, 100, 1000),
(18, 'Mr. Pearson', 7, 100, 1000),
(19, 'Reverend Swanson', 7, 100, 1000),
(20, 'Sadie Adler', 7, 100, 1000),
(21, 'Sean Macguire', 7, 100, 1000),
(22, 'Susan Grimshaw', 7, 100, 1000),
(23, 'Tilly Jackson', 7, 100, 1000),
(24, 'Uncle', 7, 100, 1000),
(25, 'Alberto Fussar', 7, 100, 1000),
(26, 'Andrew Milton', 7, 100, 1000),
(27, 'Angelo Bronte', 7, 100, 1000),
(28, 'Catherine Braithwaite', 7, 100, 1000),
(29, 'Colm O''Driscoll', 7, 100, 1000),
(30, 'Colonel Henry Favours', 7, 100, 1000),
(31, 'Edgar Ross', 7, 100, 1000),
(32, 'Guido Martelli', 7, 100, 1000),
(33, 'Leigh Gray', 7, 100, 1000),
(34, 'Levi Simon', 7, 100, 1000),
(35, 'Leviticus Cornwall', 7, 100, 1000),
(36, 'Angus Geddes', 7, 100, 1000),
(37, 'Archibald Macgregor', 7, 100, 1000),
(38, 'Beau Gray', 7, 100, 1000),
(39, 'Brother Dorkins', 7, 100, 1000),
(40, 'Captain Lyndon Monroe', 7, 100, 1000),
(41, 'Cleet', 7, 100, 1000),
(42, 'David Geddes', 7, 100, 1000),
(43, 'Duncan Geddes', 7, 100, 1000),
(44, 'Eagle Flies', 7, 100, 1000),
(45, 'Hercule Fontaine', 7, 100, 1000),
(46, 'Jamie Gillis', 7, 100, 1000),
(47, 'Joe', 7, 100, 1000),
(48, 'Mary Linton', 7, 100, 1000),
(49, 'Mr. Gillis', 7, 100, 1000),
(50, 'Mrs. Geddes', 7, 100, 1000),
(51, 'Paytah', 7, 100, 1000),
(52, 'Penelope Braithwaite', 7, 100, 1000),
(53, 'Rains Fall', 7, 100, 1000),
(54, 'Sister Calderón', 7, 100, 1000),
(55, 'Tavish Gray', 7, 100, 1000),
(56, 'Tom Dickens', 7, 100, 1000),
(57, 'Algie Davison', 7, 100, 1000),
(58, 'Archie Downes', 7, 100, 1000),
(59, 'Chick Matthews', 7, 100, 1000),
(60, 'Cooper', 7, 100, 1000),
(61, 'Edith Downes', 7, 100, 1000),
(62, 'Gwyn Hughes', 7, 100, 1000),
(63, 'J. John Weathers', 7, 100, 1000),
(64, 'Lilly Millet', 7, 100, 1000),
(65, 'Mrs. Londonderry', 7, 100, 1000),
(66, 'Thomas Downes', 7, 100, 1000),
(67, 'Winton Holmes', 7, 100, 1000),
(68, 'Wrobel', 7, 100, 1000),
(69, 'Acrisius', 7, 100, 1000),
(70, 'Albert Mason', 7, 100, 1000),
(71, 'Algernon Wasp', 7, 100, 1000),
(72, 'Anders Helgerson', 7, 100, 1000),
(73, 'Andrew Bell Iii', 7, 100, 1000),
(74, 'Bertram', 7, 100, 1000),
(75, 'Bray Aberdeen', 7, 100, 1000),
(76, 'Charles Châtenay', 7, 100, 1000),
(77, 'Charlotte Balfour', 7, 100, 1000),
(78, 'Chelonian Master', 7, 100, 1000),
(79, 'Deborah Macguiness', 7, 100, 1000),
(80, 'Dr. Alphonse Renaud', 7, 100, 1000),
(81, 'Edmund Lowry Jr.', 7, 100, 1000),
(82, 'Evelyn Miller', 7, 100, 1000),
(83, 'Francis Sinclair', 7, 100, 1000),
(84, 'Hamish Sinclair', 7, 100, 1000),
(85, 'Helen', 7, 100, 1000),
(86, 'Hermit', 7, 100, 1000),
(87, 'Hermit Woman', 7, 100, 1000),
(88, 'James Langton', 7, 100, 1000),
(89, 'Jeremiah Compson', 7, 100, 1000),
(90, 'Jeremy Gill', 7, 100, 1000),
(91, 'Jimmy Brooks', 7, 100, 1000),
(92, 'Magnifico', 7, 100, 1000),
(93, 'Margaret', 7, 100, 1000),
(94, 'Marko Dragic', 7, 100, 1000),
(95, 'Máximo Cristóbal Valdespino', 7, 100, 1000),
(96, 'Miss Marjorie', 7, 100, 1000),
(97, 'Mrs. L. Hobbs', 7, 100, 1000),
(98, 'Nigel (Gavin''S Friend)', 7, 100, 1000),
(99, 'Obediah Hinton', 7, 100, 1000),
(100, 'Phineas T. Ramsbottom', 7, 100, 1000),
(101, 'Proetus', 7, 100, 1000),
(102, 'Professor Shiftacre', 7, 100, 1000),
(103, 'Sally Nash', 7, 100, 1000),
(104, 'Sampson Black', 7, 100, 1000),
(105, 'Tammy Aberdeen', 7, 100, 1000),
(106, 'Theodore Levin', 7, 100, 1000),
(107, 'Tommy', 7, 100, 1000),
(108, 'Vampire', 7, 100, 1000),
(109, 'Wendell White', 7, 100, 1000),
(110, 'Billy Midnight', 7, 100, 1000),
(111, 'Black Belle', 7, 100, 1000),
(112, 'Emmet Granger', 7, 100, 1000),
(113, 'Flaco Hernandez', 7, 100, 1000),
(114, 'Jim "Boy" Calloway', 7, 100, 1000),
(115, 'Slim Grant', 7, 100, 1000),
(116, 'Albert Cakes', 7, 100, 1000),
(117, 'Alden Carruthers', 7, 100, 1000),
(118, 'Aldridge T. Abbington', 7, 100, 1000),
(119, 'Ansel Atherton', 7, 100, 1000),
(120, 'Arturo Bullard', 7, 100, 1000),
(121, 'Benjamin Lambert', 7, 100, 1000),
(122, 'Clay Davies', 7, 100, 1000),
(123, 'Clive Davies', 7, 100, 1000),
(124, 'Curtis Malloy', 7, 100, 1000),
(125, 'Devon', 7, 100, 1000),
(126, 'Hanley', 7, 100, 1000),
(127, 'Harmon Thomas', 7, 100, 1000),
(128, 'Hector Barlow', 7, 100, 1000),
(129, 'Henri Lemieux', 7, 100, 1000),
(130, 'Herbert Moon', 7, 100, 1000),
(131, 'Oswald Dunbar', 7, 100, 1000),
(132, 'Palmer', 7, 100, 1000),
(133, 'Sam Freeman', 7, 100, 1000),
(134, 'Seamus', 7, 100, 1000),
(135, 'Thomas "Skiff Captain"', 7, 100, 1000),
(136, 'Trapper', 7, 100, 1000),
(137, 'Vernon Farley', 7, 100, 1000),
(138, 'Willard Wayne', 7, 100, 1000),
(139, 'Anthony Foreman', 7, 100, 1000),
(140, 'Benedict Allbright', 7, 100, 1000),
(141, 'Elias Green', 7, 100, 1000),
(142, 'Ellie Anne Swan', 7, 100, 1000),
(143, 'Esteban Cortez', 7, 100, 1000),
(144, 'Joaquin Arroyo', 7, 100, 1000),
(145, 'Joshua Brown', 7, 100, 1000),
(146, 'Lindsey Wofford', 7, 100, 1000),
(147, 'Mark Johnson', 7, 100, 1000),
(148, 'Marshall Thurwell', 7, 100, 1000),
(149, 'Nathan Kirk', 7, 100, 1000),
(150, 'Otis Skinner', 7, 100, 1000),
(151, 'Ramón Cortez', 7, 100, 1000),
(152, 'Robbie Laidlaw', 7, 100, 1000),
(153, 'Shane Finley', 7, 100, 1000),
(154, 'Wilson J. Mcdaniels', 7, 100, 1000),
(155, 'Alden Carruthers', 7, 100, 1000),
(156, 'Alfredo Montez', 7, 100, 1000),
(157, 'Amos Lancing', 7, 100, 1000),
(158, 'Anthony Foreman', 7, 100, 1000),
(159, 'Black Belle', 7, 100, 1000),
(160, 'Bonnie Macfarlane', 7, 100, 1000),
(161, 'Bray Aberdeen', 7, 100, 1000),
(162, 'Clay Davies', 7, 100, 1000),
(163, 'Clive Davies', 7, 100, 1000),
(164, 'Curtis Malloy', 7, 100, 1000),
(165, 'Flaco Hernandez', 7, 100, 1000),
(166, 'Guido Martelli', 7, 100, 1000),
(167, 'Gus Macmillan', 7, 100, 1000),
(168, 'Hamish Sinclair', 7, 100, 1000),
(169, 'Harriet Davenport', 7, 100, 1000),
(170, 'Hector Barlow', 7, 100, 1000),
(171, 'Jake Adler', 7, 100, 1000),
(172, 'James Langton', 7, 100, 1000),
(173, 'Jb Cripps', 7, 100, 1000),
(174, 'Jeremiah Shaw', 7, 100, 1000),
(175, 'Jessica Leclerk', 7, 100, 1000),
(176, 'Joe', 7, 100, 1000),
(177, 'Jorge Montez', 7, 100, 1000),
(178, 'Josiah Trelawny', 7, 100, 1000),
(179, 'Madam Nazar', 7, 100, 1000),
(180, 'Maggie Fike', 7, 100, 1000),
(181, 'Marshal Tom Davies', 7, 100, 1000),
(182, 'Mr. Horley', 7, 100, 1000),
(183, 'Old Man Jones', 7, 100, 1000),
(184, 'Sadie Adler', 7, 100, 1000),
(185, 'Sam Freeman', 7, 100, 1000),
(186, 'Samson Finch', 7, 100, 1000),
(187, 'Seamus', 7, 100, 1000),
(188, 'Sean Macguire', 7, 100, 1000),
(189, 'Shaky', 7, 100, 1000),
(190, 'Tammy Aberdeen', 7, 100, 1000),
(191, 'Teddy Brown', 7, 100, 1000),
(192, 'The Woman With No Name', 7, 100, 1000),
(193, 'Thomas "Skiff Captain"', 7, 100, 1000);

-- Gerando apenas as instâncias de NPC que são líderes de gangues
insert into instancia_npc
(idPersonagem, idGangue, idInventario, idMissao, idCidade)
values
(5, null, 1, NULL, 11),  -- Dutch Van Der Linde (Van Der Linde Gang) - Valentine
(29, null, 2, NULL, 3),  -- Colm O'Driscoll (O'Driscolls) - Blackwater
(166, null, 3, NULL, 8), -- Guido Martelli (Italian Mafia) - Saint Denis
(153, null, 4, NULL, 6), -- Shane Finley (Laramie Gang) - Mount Hagen
(161, null, 5, NULL, 2), -- Bray Aberdeen (Aberdeen Family) - Armadillo
(149, null, 6, NULL, 10), -- Nathan Kirk (Murfree Brood) - Tumbleweed
(151, null, 7, NULL, 5), -- Ramón Cortez (Del Lobos) - Lagras
(160, null, 8, NULL, 9); -- Bonnie Macfarlane (Ranchers) - Strawberry


insert into instancia_estabelecimento
(idEstab, idCidade, idDono)
values
();

insert into ataque
(descricao, dano)
values
();

insert into animal_tipo
(tipo)
values
('AMG'),
('HST');

--Parei aqui

insert into item_tipo
(idItem, tipo)
values
(1, 'CON'),
(2, 'CON'),
(3, 'CON'),
(4, 'CON'),
(5, 'CON'),
(6, 'CON'),
(7, 'CON'),
(8, 'CON'),
(9, 'CON'),
(10, 'CON'),
(11, 'CON'),
(12, 'CON'),
(13, 'CON'),
(14, 'CON'),
(15, 'CON'),
(16, 'CON'),
(17, 'EQP'),
(18, 'EQP'),
(19, 'EQP'),
(20, 'EQP'),
(21, 'EQP'),
(22, 'EQP'),
(23, 'EQP'),
(24, 'AFG'),
(25, 'AFG'),
(26, 'AFG'),
(27, 'AFG'),
(28, 'AFG'),
(29, 'AFG'),
(30, 'AFG'),
(31, 'AFG'),
(32, 'AFG'),
(33, 'AFG'),
(34, 'AFG'),
(35, 'AFG'),
(36, 'AFG'),
(37, 'AFG'),
(38, 'AFG'),
(39, 'AFG'),
(40, 'AFG'),
(41, 'AFG'),
(42, 'AFG'),
(43, 'AFG'),
(44, 'AFG'),
(45, 'AFG'),
(46, 'AFG'),
(47, 'AFG'),
(48, 'AFG'),
(49, 'AFG'),
(50, 'AFG'),
(51, 'AFG'),
(52, 'AFG'),
(53, 'AFG'),
(54, 'AFG'),
(55, 'AFG'),
(56, 'AFG'),
(57, 'AFG'),
(58, 'AFG'),
(59, 'AFG'),
(60, 'AML'),
(61, 'AML'),
(62, 'AML'),
(63, 'AML'),
(64, 'AML'),
(65, 'AML'),
(66, 'AML'),
(67, 'AML'),
(68, 'AML'),
(69, 'AML'),
(70, 'AML'),
(71, 'AML'),
(72, 'AML'),
(73, 'AML'),
(74, 'AML'),
(75, 'AML'),
(76, 'AML'),
(77, 'AML'),
(78, 'AML'),
(79, 'AML'),
(80, 'AML'),
(81, 'AML'),
(82, 'AML');

INSERT INTO item_consumivel (idItem, nome, descricao, peso, preco, durabilidadeMaxima, qtdReparacaoStamina, qtdReparacaoVida)
VALUES 
(1, 'Feijão Assado', 'Lata de feijão assado', 2, 1.50, NULL, 25, 10),
(2, 'Pêssegos em Calda', 'Lata de pêssegos', 2, 1.75, NULL, 15, 10),
(3, 'Milho Doce em Lata', 'Lata de milho doce', 2, 1.50, NULL, 20, 10),
(4, 'Tabaco de Mascar', 'Tabaco de mascar', 1, 0.50, NULL, 15, 5),
(5, 'Cura de Saúde', 'Tônico de saúde', 1, 3.00, NULL, 0, 100),
(6, 'Cura Potente de Saúde', 'Tônico potente de saúde', 1, 4.50, NULL, 0, 150),
(7, 'Tônico Milagroso', 'Tônico milagroso', 2, 5.00, NULL, 50, 50),
(8, 'Tônico Milagroso Potente', 'Tônico potente milagroso', 2, 6.00, NULL, 75, 75),
(9, 'Bolachas de Aveia', 'Bolachas de aveia', 1, 1.00, NULL, 10, 5),
(10, 'Cigarros Premium', 'Cigarros premium', 1, 2.50, NULL, 20, 0),
(11, 'Conhaque Fino', 'Conhaque fino', 3, 7.50, NULL, 30, 30),
(12, 'Gim', 'Gim', 3, 3.00, NULL, 25, 25),
(13, 'Rum', 'Rum', 3, 4.00, NULL, 20, 20),
(14, 'Óleo de Cobra', 'Óleo de cobra', 1, 2.00, NULL, 10, 10),
(15, 'Óleo de Cobra Potente', 'Óleo de cobra potente', 1, 3.00, NULL, 15, 15),
(16, 'Uísque', 'Uísque', 3, 3.50, NULL, 25, 25);

insert into item_equipavel
(idItem, nome, descricao, peso, preco, durabilidadeMaxima, parteDoCorpo)
values
(17, 'Chapéu de Couro', 'Chapéu feito de couro durável.', 2, 10.00, 100, 'Cabeça'),
(18, 'Colete de Couro', 'Colete resistente para proteção extra.', 3, 15.00, 120, 'Tronco'),
(19, 'Botas de Couro', 'Botas robustas feitas de couro.', 4, 12.00, 100, 'Pés'),
(20, 'Luvas de Couro', 'Luvas que oferecem boa proteção e aderência.', 1, 5.00, 80, 'Mãos'),
(21, 'Jaqueta de Peles', 'Jaqueta feita de peles para proteção contra o frio.', 5, 25.00, 150, 'Tronco'),
(22, 'Cinto de Munição', 'Cinto para carregar munição extra.', 2, 8.00, 90, 'Cintura'),
(23, 'Esporas de Metal', 'Esporas que aumentam a eficácia ao montar.', 1, 7.00, 60, 'Pés');

insert into arma_fogo
(nome, descricao, peso, preco, durabilidadeMaxima, danoPorAtaque, velocidadeDisparo, velocidadeReload)
(24, 'Revolver de Algernon','O revólver do Algernon é uma arma na classe Revolver apresentada no modo de história de Red Dead Redemption 2. O design do revólver do Algernon é baseado em um novo modelo de exército e marinho da vida real.A versão do jogo da arma é fabricada pela D.D.Packenbush.Esta arma não pode ser personalizada.O revólver do Algernon só pode ser obtido no modo de história do RDR2 como uma recompensa de bônus.Ele fica disponível após concluir as duquesas missionárias e outros animais (colecionáveis ​​exóticos) no modo de história.Um raro revólver de ação dupla, com um barril curto compacto, um trabalho decorativo de gravação de ouro e uma garra de pérola exclusiva esculpida à mão.Isso anteriormente pertencia à Argernon Wasp, um colecionador de itens exóticos em Saint Denis.Essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e revólver explosivo.Em breve.', 4, 0.889, 51, 38.00, 82.00, 70.00, 50.00),
(25, 'Rifle de ação de parafuso','O rifle de ação de parafuso é uma arma na aula de rifles apresentada em Red Dead Redemption 2 e Red Dead Online.O design do rifle de ação de parafuso é baseado em um rifle de Krag-Jørgensen, modelo de Springfield 1892 da vida real.A versão do jogo da arma é fabricada por B.D.& Co .. Esta arma pode ser personalizada em qualquer um dos armeiros.O rifle de ação de parafuso pode ser comprado em Red Dead on-line em qualquer armeiro ou no catálogo de mão, por um preço de US $ 216,00 ou 9 barras de ouro.É desbloqueado para compra depois de atingir o Rank 7 em Red Dead Online.O rifle de ação de parafuso pode ser comprado no modo de história RDR2 no Gunsmith por um preço de US $ 180,00.Ele fica disponível depois de concluir a missão que prega o perdão enquanto ele entrou no modo de história.O B.D.& Co. Bolt Action é um rifle forte e versátil, construído para executar em qualquer ambiente.O mecanismo de ação de parafuso permite disparar e recarregar rápido, tornando este rifle uma escolha ideal para combate de longo alcance com vários alvos.Essa arma tem uma capacidade de munição de cinco rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e rifle explosivo.Olhe para baixo através das vistas.Sinta o estoque de armas.Amigo, não há melhor rifle de ação parafuso em nenhuma loja ou fornecedor disponível do que o B.D & Co. tem certeza de que não hesitará em preencher o destinatário cheio de quantidades iguais de chumbo e pavor.Em breve.', 5, 0.541, 79, 72.00, 37.00, 55.00, 82.00),
(26, 'Revolver de Calloway','O revólver do Calloway é uma arma na classe dos revólveres apresentada no modo Story of Red Dead Redemption 2. O design do revólver do Calloway é baseado em um revólver da vida real Smith & Wesson Modelo 3 "Schofield".A versão do jogo da arma é fabricada pela Hutton & Baird.Esta arma não pode ser personalizada.O revólver do Calloway só pode ser obtido no modo de história do RDR2 como uma recompensa de bônus.Ele fica disponível depois de concluir a missão o mais nobre dos homens e uma mulher (pistoleiros) no modo de história.Complete a etapa final da missão estranha "o mais nobre do homem e uma mulher" e colete a arma perto do cadáver de Jim "Boy" Calloway após o seu duelo.Se você não pegar, não poderá adquiri -lo mais tarde.Um raro revólver Schofield banhado em prata, com "Canis Canem editar" gravado na lateral do barril.Essa lateral anteriormente pertencia ao Gunslinger Jim "Boy" Calloway, anteriormente pertencente ao Gunslinger Jim "Boy" Calloway, essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto dividido, expressar e explosivo.Em breve.', 1, 0.651, 57, 46.00, 70.00, 64.00, 75.00),
(27, 'Repetidor de carabina','O Repetidor de Carbine é uma arma na aula de repetidores apresentada em Red Dead Redemption 2 e Red Dead Online.O design do repetidor de carabinas é baseado em uma carabina do Modelo Spencer da Vida Real 1865.A versão do jogo da arma é fabricada por Buck.Esta arma pode ser personalizada em qualquer um dos armeiros.O repetidor de carabinas pode ser comprado em Red Dead on -line em qualquer armeiro ou no catálogo portátil, por um preço de US $ 90,00 ou 4 barras de ouro.O repetidor de carabinas pode ser comprado no modo de história do RDR2 no Gunsmith por um preço de US $ 90,00.Ele fica disponível depois de concluir os velhos amigos da missão no modo de história.Um rifle de repetição confiável e popular, o Buck Carbine oferece danos médios e uma taxa de disparo decente, com velocidades rápidas de recarga, graças à revista carregada de tubo no estoque da arma.Uma opção boa e equilibrada para o combate de caça e de médio alcance, esta arma tem uma capacidade de munição de sete rodadas e pode usar munição regular, de alta velocidade, ponto dividido, expresso e repetidor explosivo.Se você estiver no mercado para um rifle repetido, não pode fazer nada errado ao trocar seu dinheiro arduamente ganho pelo repetidor de carabinas de Buck.Há pouco no mundo mais confiável, exceto um corcel de confiança ou um bom cachorro.No entanto, esses são morrer, diferentemente de uma arma finamente feita.Em breve.', 7, 0.548, 68, 60.00, 53.00, 73.00, 73.00),
(28, 'Rifle Carcano','O rifle Carcano é uma arma na aula de rifles de sniper apresentada em Red Dead Redemption 2 e Red Dead Online.O design do rifle Carcano é baseado em um rifle curto do Modelo 91/38 da Vida Real Carcano.A versão do jogo da arma é fabricada pelo Sireno.Esta arma pode ser personalizada em qualquer um dos armeiros.O rifle Carcano pode ser comprado em Red Dead on -line em qualquer armeiro ou no catálogo portátil, por um preço de US $ 456,00 ou 19 barras de ouro.É desbloqueado para compra depois de atingir o Rank 50 em Red Dead Online.O rifle Carcano pode ser comprado no modo de história do RDR2 no Gunsmith por um preço de US $ 190,00.Ele fica disponível depois de concluir o adeus da missão, querido amigo no modo de história.O Sireno Carcano é um longo rifle de ação de parafuso com escopo que pode conter várias rodadas de uma só vez.Quando combinado com a taxa de disparo rápido e a rápida velocidade de recarga, isso o torna ideal para enfrentar vários inimigos em combate de longa distância.Essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e rifle explosivo.Rifle de escolha para ambição sagrada e profana.Foi dito que a discrição é a melhor parte da bravura, e não é exibido mais bravura do que o de um homem escondido atrás de uma rocha e tirando seus inimigos quando eles menos suspeitam.Você não pode encontrar rifle melhor do que o rifle Carcano.Em breve.', 5, 0.704, 60, 75.00, 40.00, 70.00, 85.00),
(29, 'Cattleman Revolver','O Cattleman Revolver é uma arma na classe dos revólveres apresentada em Red Dead Redemption 2 e Red Dead Online.O design do revólver de gatinho é baseado em um revólver do Exército de Ação Única do Modelo 1873 da Vida Real 1873.A versão do jogo da arma é fabricada por Buck.Esta arma pode ser personalizada em qualquer um dos armeiros.O Cattleman Revolver pode ser adquirido em Red Dead online em qualquer armeiro ou no catálogo portátil, por um preço de US $ 50,00 ou 2 barras de ouro.O revólver Cattleman pode ser comprado no modo de história do RDR2 no Gunsmith por um preço de US $ 50,00.Ele fica disponível depois de concluir os bandidos da missão do oeste no modo de história.Disponível desde o início do jogo.Uma lateral popular e clássica, o Buck Cattleman é um ótimo revólver geral, apresentando um bom equilíbrio de dano, precisão e taxa de incêndio.Adequado para combate próximo a médio alcance, esta arma também pode ser empunhada dupla e usada a cavalo.Essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e revólver explosivo.Não há um revólver melhor para ter ao seu lado ao ir para o oeste na terra do leite e do mel.Fan the Hammer em rápida sucessão e você verá a rapidez com que esse revólver pode ser descarregado para os desanimados surpresos com os outros.Armas: Cattleman Revolver', 5, 0.298, 50, 42.00, 75.00, 67.00, 67.00),
(30, 'Revolver de ação dupla','O revólver de ação dupla é uma arma na classe dos revólveres apresentada em Red Dead Redemption 2 e Red Dead Online.O design do revólver de ação dupla é baseado em um novo Modelo 1892 Army & Navy Revolver da vida real.A versão do jogo da arma é fabricada pela D.D.Packenbush.Esta arma pode ser personalizada em qualquer um dos armeiros.Esta arma também aparece no GTA online.O revólver de ação dupla pode ser comprado em Red Dead online em qualquer armeiro ou no catálogo de mão, por um preço de US $ 127,00 ou 6 barras de ouro.É desbloqueado para compra depois de atingir o Rank 17 em Red Dead Online.O revólver de ação dupla pode ser comprado no modo de história RDR2 no Gunsmith por um preço de US $ 65,00.Fica disponível depois de concluir a missão, uma gentileza estranha no modo de história.Jogadores que concluíram a caça ao tesouro on-line do GTA relacionados e executaram 50 tiros na cabeça com o revólver de ação dupla no GTA on-line, receberão um revólver de ação dupla pré-moldada em seu inventário RDR2 após "Limite Leste" (Capítulo 1) e eSerá os únicos a ter acesso à cor do metal dourado para personalizar esta arma.O D.D.A ação dupla Packenbush é um revólver de disparo rápido com danos médios.O mecanismo avançado impede a necessidade de prender, com o custo de um gatilho pesado e menor precisão.A taxa rápida de incêndio faz desta uma boa escolha para combate montado.Essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e revólver explosivo.Você não pode encontrar um design mais bonito, atualizado do que o revólver de ação dupla D.D Packenbush.Ele tem a melhor ação de qualquer revólver pelo preço e, quando você pedir um, você será o juiz, o júri e, muito provavelmente, o executor.Este vídeo mostra onde encontrar o revólver de ação dupla em Red Dead Redemption 2:', 4, 0.637, 63, 38.00, 82.00, 70.00, 50.00),
(31, 'Espingarda de cano duplo','A espingarda de cano duplo é uma arma na aula de espingardas apresentada em Red Dead Redemption 2 e Red Dead Online.O design da espingarda de cano duplo é baseado em uma espingarda de martelo do Modelo 1878 da vida real.A versão do jogo da arma é fabricada pela D.D.Packenbush.Esta arma pode ser personalizada em qualquer um dos armeiros.A espingarda de cano duplo pode ser comprado em Red Dead online em qualquer armeiro ou no catálogo de mão, por um preço de US $ 185,00 ou 8 barras de ouro.É desbloqueado para compra depois de atingir o Rank 30 em Red Dead Online.A espingarda de cano duplo pode ser comprado no modo RDR2 Story no Gunsmith por um preço de US $ 95,00.Ele fica disponível após concluir a missão que paga uma chamada social no modo de história.D.D.A espingarda de cano duplo da Packenbush é a escolha do pioneiro.Poderoso e mortal de perto, essa arma é capaz de disparar dois tiros em rápida sucessão, caindo quase qualquer alvo instantaneamente.Esta arma tem uma capacidade de munição de duas rodadas e pode usar uma batida regular, uma munição de espingarda de lesma e slug explosiva.Na verdade, é a melhor espingarda disponível hoje.Quando você entra em uma festa através das montanhas, planícies e passes desta grande terra, há apenas uma coisa que pode garantir sua segurança, e essa é a espingarda de barril duplo de D.D.Packenbush.Acredite nisso.Em breve.', 1, 0.659, 78, 65.00, 60.00, 45.00, 30.00),
(32, 'Rifle de elefante','O rifle de elefante é uma arma na aula de rifles apresentada exclusivamente em Red Dead Online, adicionado ao jogo como parte do 1.20 A atualização naturalista em 28 de julho de 2020. A versão no jogo da arma é fabricada por Mühlberg.Esta arma pode ser personalizada em qualquer um dos armeiros.O rifle de elefante pode ser comprado em Red Dead on -line em qualquer armeiro ou do catálogo de mão, por um preço de US $ 580,00 ou 24 barras de ouro.O rifle de pistola de elefante de Mühlberg é uma maravilha da fabricação e tem sido comparado a segurar um canhão.Dispare -o e veja se você ainda está de pé ou é capaz de ouvir outra coisa que não tocar por vários dias.', 8, 0.834, 54, 90.00, 40.00, 45.00, 37.00),
(33, 'Evans Repeater','The Evans Repeater é uma arma na aula de repetidores apresentada em Red Dead Redemption 2 e Red Dead Online, adicionado ao jogo como parte da atualização de 1,06 de fevereiro de 2019 em 5 de março de 2019. O design do Evans Repeater é baseado em um realLife Evans repetindo rifle.A versão do jogo da arma é fabricada por B.D.& Co .. Esta arma pode ser personalizada em qualquer um dos armeiros.O Repetidor de Evans pode ser comprado em Red Dead on -line em qualquer armeiro ou no catálogo portátil, por um preço de US $ 300,00 ou 12 barras de ouro.O repetidor de Evans pode ser comprado no modo de história do RDR2 no Gunsmith por um preço de US $ 140,00.Ele fica disponível após concluir a destilação da Missão Americana no modo de história.O rifle Evans Repeater tem uma alta capacidade de bala e é devastador a médio e longo alcance, com uma taxa de incêndio especialmente alta.Essa arma pode usar munição regular, de alta velocidade, ponto dividido, expresso e repetidor explosivo.Ele também possui opções de personalização, incluindo ações, pontos turísticos e envoltórios.O Evans Repeater é um poderoso rifle de longo alcance que é conhecido por estar no arsenal de John Marston durante os eventos do primeiro jogo de resgate Red Dead.O novo e aprimorado Evans Repeater é o rifle de repetição de mais alta qualidade já divulgado por B.D.e Co. É sabido que essa fina de armas de fogo mecanizada requer pouca aptidão acadêmica.Simplesmente grite um suplemento, puxe o gatilho e repita.Em breve.', 1, 0.458, 56, 50.00, 62.00, 62.00, 74.00),
(34, 'Revolver de Flaco','O revólver do Flaco é uma arma na classe dos revólveres apresentada no modo Story of Red Dead Redemption 2. O design do revólver do Flaco é baseado em um revólver de ação única do Modelo 1873 da Life 1873.A versão do jogo da arma é fabricada por Buck.Esta arma não pode ser personalizada.O revólver do Flaco só pode ser obtido no modo de história do RDR2 como uma recompensa de bônus.Ele fica disponível depois de concluir a missão o mais nobre dos homens e uma mulher (pistoleiros) no modo de história.Encontrado ao lado do corpo de Flaco Hernandez após seu duelo na missão de pistolas correspondente.Se você não pegar, não poderá adquiri -lo mais tarde.Um raro revólver de pecuarista, com delicadas gravuras e uma alça de marfim esculpida.Anteriormente de propriedade de Gunslinger Flaco Hernandez, derrotado em um duelo em Cairn Lake, essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto dividido, expresso e explosivo.Em breve.', 7, 0.72, 93, 42.00, 75.00, 67.00, 67.00),
(35, 'Revolver de Granger','O revólver do Granger é uma arma na classe dos revólveres apresentada no modo Story of Red Dead Redemption 2. O design do revólver do Granger é baseado em um revólver do Exército de Ação Única do Modelo 1873 da vida real.A versão do jogo da arma é fabricada por Buck.Esta arma não pode ser personalizada.O revólver do Granger só pode ser obtido no modo de história do RDR2 como uma recompensa de bônus.Ele fica disponível depois de concluir a missão o mais nobre dos homens e uma mulher (pistoleiros) no modo de história.Encontrado ao lado do corpo de Emmet Granger após seu duelo na missão de pistolas correspondente.Se você não pegar, não poderá adquiri -lo mais tarde.Um revólver raro de pecuarista, com um acabamento de metal escuro e coberto de gravuras personalizadas.Anteriormente de propriedade do Gunslinger Emmet Granger, derrotado em um duelo perto da estação dekneck, essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto dividido, expresso e revólver explosivo.Em breve.', 8, 0.545, 82, 42.00, 75.00, 67.00, 67.00),
(36, 'Revólver de ação dupla de alto rolo','O revólver de ação dupla de alto rolo é uma arma na classe dos revólveres apresentada em Red Dead Redemption 2 e Red Dead Online.O design do revólver de ação dupla de alto rolador é baseado em um revólver do Exército e da Marinha do Exército e da Marinha do Colt da vida real.A versão do jogo da arma é fabricada pela D.D.Packenbush.Esta arma não pode ser personalizada.O revólver de ação dupla de alto rolo pode ser adquirido em Red Dead on-line a qualquer cerca por um preço de US $ 190,00 ou 8 barras de ouro.O revólver de ação dupla de alto rolo pode ser adquirido no modo RDR2 Story na cerca por um preço de US $ 81,00.A aparência pode matar: o revólver de ação dupla de alto rolo apresenta um corpo de aço polido com um trabalho exclusivo de gravura, inspirado em período, inspirado em período.O revólver de empate rápido e mortal vem completo com cartas de jogo exclusivas e elementos de crânio esculpidos no aperto.Sua taxa de incêndio superior e superior sobre todos os outros revólveres o torna uma ótima opção para combate montado.Em breve.', 3, 0.97, 81, 38.00, 82.00, 70.00, 50.00),
(37, 'REVOLVER CATTLEMAN de John','O Cattleman Revolver de John é uma arma na classe dos revólveres apresentada no modo Story of Red Dead Redemption 2. O design do revólver de john''s Cattleman é baseado em um revólver de exército de ação único da vida real.A versão do jogo da arma é fabricada por Buck.Esta arma não pode ser personalizada.Ele fica disponível após a conclusão do epílogo da missão - parte 1 no modo de história.De propriedade de John Marston, este revólver personalizado de Cattleman apresenta um acabamento de aço enegrecido e um punho de osso personalizado.No entanto, depois de anos de pistolas imprudentes e crimes, essa lateral viu dias melhores.Essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e revólver explosivo.Em breve.', 3, 0.405, 85, 42.00, 75.00, 67.00, 67.00),
(38, 'Repetidor de Lancaster','O Lancaster Repeater é uma arma na aula de repetidores apresentada em Red Dead Redemption 2 e Red Dead Online.O design do Lancaster Repeater é baseado em uma carabina do Modelo 1866 da Vida Real Winchester.A versão do jogo da arma é fabricada por Lancaster.Esta arma pode ser personalizada em qualquer um dos armeiros.O Repetidor de Lancaster pode ser comprado em Red Dead online em qualquer armeiro ou no catálogo de mão, por um preço de US $ 243,00 ou 10 barras de ouro.Ele é desbloqueado para compra depois de atingir o Rank 12 em Red Dead Online.O Repetidor de Lancaster pode ser comprado no modo de história do RDR2 no Gunsmith por um preço de US $ 135,00.Fica disponível depois de concluir a missão uma cena pastoral americana no modo de história.O Lancaster Repeater é uma arma completa que usa um sistema de ação de alavanca rápida para carregar o próximo cartucho.Pode ter danos mais baixos em comparação com outros rifles de repetição, mas a taxa de disparo rápido e a boa precisão dão a vantagem.Essa arma tem uma capacidade de munição de quatorze rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e repetidor explosivo.A arma que ganhou o oeste e o sul de Ne''er-Do-Wells.Recebemos cartas de milhares de compradores satisfeitos que dizem que o poder de fogo superior do Lancaster é satisfatório em todas as formas.Em breve.', 5, 0.666, 90, 55.00, 59.00, 70.00, 76.00),
(39, 'Lemat Revolver','O Revolver Lemat é uma arma na classe Revolvadores apresentada em Red Dead Redemption 2 e Red Dead Online, adicionado ao jogo como parte da atualização de 1,09 de maio de 2019 em 14 de maio de 2019. O design do revólver Lemat é baseado em um realLife Lemat Revolver.A versão do jogo da arma é fabricada pela D.D.Packenbush.Esta arma pode ser personalizada em qualquer um dos armeiros.O revólver Lemat pode ser comprado em Red Dead online em qualquer armeiro ou no catálogo de mão, por um preço de US $ 317,00 ou 13 barras de ouro.O revólver LEMAT pode ser comprado no modo RDR2 Story no Gunsmith por um preço de US $ 155,00.Ele fica disponível após concluir a missão a gaiola dourada no modo de história.Com uma câmara giratória de 9 rodadas e um barril secundário para uma única rodada de buckshot, alterne entre balas de fogo rápido e uma devastadora espingarda em tempo real com o revólver Lemat-agora disponível para compra do catálogo Wheeler, Rawson e Co.Este revólver exclusivo, com seu segundo barril para Buck Shot, é tão forte e tão perfeito na fabricação, ainda não gravamos um que tenha se tornado instável ou solto.Dire cinquenta mil rodadas com precisão impecável e você verá.O Lemat Revolver é o vencedor de curto alcance.Em breve.', 4, 0.881, 66, 50.00, 60.00, 58.00, 68.00),
(40, 'Repetidor de Litchfield','O Litchfield Repeater é uma arma na aula de repetidores apresentada em Red Dead Redemption 2 e Red Dead Online.O design do repetidor de Litchfield é baseado em um rifle de repetição de Henry na vida real.A versão do jogo da arma é fabricada por Litchfield.Esta arma pode ser personalizada em qualquer um dos armeiros.O repetidor de Litchfield pode ser comprado em Red Dead online em qualquer armeiro ou no catálogo de mão, por um preço de US $ 348,00 ou 14 barras de ouro.É desbloqueado para compra depois de atingir o Rank 18 em Red Dead Online.O repetidor de Litchfield pode ser comprado no modo de história do RDR2 no Gunsmith por um preço de US $ 145,00.Ele fica disponível depois de concluir o adeus da missão, querido amigo no modo de história.O repetidor de Litchfield é uma ótima opção para a caça, com o melhor dano de todos os rifles repetidos e uma grande capacidade de munição.Apesar de uma taxa de incêndio mais lenta e velocidade de recarga, o Litchfield se destaca em combate de médio alcance;Perfeito ao precisar limpar uma área.Essa arma tem uma capacidade de munição de dezesseis rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e repetidor explosivo.Imagine um rifle que você poderia passar horas limpando com amor em uma tarde de domingo, depois carregue com cartuchos e atirasse durante toda a semana sem ter que recarregar.É um alívio desse tipo de preocupação que permite que um homem deixe sua mente a tarefas maiores, como entender o significado do universo.Armas: Litchfield Repeater', 5, 0.62, 94, 65.00, 50.00, 65.00, 68.00),
(41, 'Revolver de Lowry','O revólver de Lowry é uma arma na classe Revolvers apresentada exclusivamente em Red Dead Online, adicionado ao jogo como parte da atualização de 1.15 Moonshiners em 13 de dezembro de 2019. O design do revólver de Lowry é baseado em um revólver da Marinha da Life 1851 da vida real 1851.Esta arma não pode ser personalizada.Esta arma também aparece no GTA online.Para desbloquear o revólver do Lowry em Red Dead Online, você deve primeiro obter o revólver da Marinha no GTA on -line, resolvendo o mistério do Slasher Los Santos Slasher e matando o slasher.Então, você deve receber 50 mortes com o revólver da Marinha no GTA online.A conclusão da etapa on -line do GTA desbloqueará a capacidade de encontrar essa arma exclusiva, o revólver do Lowry, para uso em Red Dead Online.O revólver de Lowry pode ser encontrado no covil underground do infame assassino em série Edmund Lowry Jr, em Lucky''s Cabine, perto de Valentine.Veja o mapa abaixo para obter a localização exata.Depois de inserido no porão, você encontrará uma caixa de lock.Simplesmente abra, e a arma será sua.É uma variação personalizada exclusiva do revólver da Marinha, com marcas de sangue e gravuras de arranhões.O novo revólver de Lowry tem as melhores estatísticas médias de todos os revólveres em Red Dead Redemption 2, tornando -o o melhor revólver do jogo.Você deve primeiro desbloquear o revólver da Marinha no GTA Online (que é o modelo equivalente desta arma) para obter o revólver do Lowry em Red Dead Online.Em breve.Este vídeo mostra onde encontrar o revólver do Secret Lowry adicionado em Red Dead on -line com a atualização "1.15 Moonshiners".', 3, 0.941, 54, 52.00, 72.00, 50.00, 80.00),
(42, 'M1899 Pistola','A pistola M1899 é uma arma na classe Pistols apresentada no modo de história de Red Dead Redemption 2, adicionado ao jogo como parte da atualização de lançamento de 1,14 PC em 5 de novembro de 2019. O design da pistola M1899 é baseado em uma realLife fn Browning M1900.A versão do jogo da arma é fabricada pela Peeters & Janssens.Esta arma pode ser personalizada em qualquer um dos armeiros.A pistola M1899 pode ser comprada no modo de história RDR2 no Gunsmith por um preço de US $ 350,00.Ele fica disponível depois de concluir a missão A Batalha de Shady Belle no modo Story.A pistola M1899 é uma pistola semi-automática totalmente nova com munição carregada com clipe.É uma arma exclusiva disponível apenas no modo de história de Red Dead Redemption 2. Para desbloquear a pistola M1899, você deve primeiro concluir a missão "A Batalha de Shady Belle".Somente estocada pelo melhor armeiro de Saint Denis, o M1899 por Peeters & Janssens é uma lateral completamente moderna.Uma pistola semi-automática, o M1899 causa um bom dano em curto alcance e sua munição carregada com clipe permite uma recarga rápida.Essa arma tem uma capacidade de munição de oito rodadas e pode usar o ponto de divisão regular e de alta velocidade, a munição de pistola expressa e explosiva.Em breve.', 1, 0.868, 55, 37.50, 77.00, 78.00, 70.00),
(43, 'Pistola Mauser','A pistola Mauser é uma arma na classe Pistols apresentada em Red Dead Redemption 2 e Red Dead Online.O design da pistola Mauser é baseado em uma pistola Mauser C96 da vida real.A versão do jogo da arma é fabricada por Mühlberg.Esta arma pode ser personalizada em qualquer um dos armeiros.A pistola Mauser pode ser comprada em Red Dead on -line em qualquer armeiro ou no catálogo portátil, por um preço de US $ 600,00 ou 24 barras de ouro.Ele é desbloqueado para compra depois de atingir o Rank 34 em Red Dead Online.A pistola Mauser pode ser comprada no modo de história RDR2 no Gunsmith por um preço de US $ 250,00.Fica disponível após concluir a missão que é o país de Murfree no modo de história.Uma nova importação da Alemanha, o Mühlberg Mauser é uma pistola semi-automática moderna com baixos danos.A rápida taxa de incêndio dessa arma, juntamente com uma grande capacidade de munição, faz desta uma boa escolha para combate de perto ou quando cercado por vários inimigos.Essa arma tem uma capacidade de munição de dez rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e pistola explosiva.A melhor pistola "automática" auto -carregada.Ele tem os designs mais - tendo se originado de dois irmãos apaixonados na Europa que passaram o trabalho de sua vida formando maneiras engenhosas de impulsionar liderar a altas taxas de velocidade.Em breve.', 5, 0.763, 97, 36.00, 80.00, 75.00, 62.00),
(44, 'Revolver de Micah','O revólver do Micah é uma arma na classe dos revólveres apresentada no modo Story of Red Dead Redemption 2. O design do revólver do Micah é baseado em um revólver do Exército e da Marinha da Vida Real Colt.A versão do jogo da arma é fabricada pela D.D.Packenbush.Esta arma não pode ser personalizada.O revólver do Micah só pode ser obtido no modo de história do RDR2 como uma recompensa de bônus.Ele fica disponível após concluir a missão American Venom no modo de história.Story Spoiler: Retorne ao local do tiroteio final no topo Mount Hagen após o "American Venom" (Epílogo 2) e recupere a arma do cadáver congelado, este velho revólver de ação dupla apresenta uma estrutura de aço enegrecida e um vermelho personalizado e vermelho e-Brepa de crânio preta.Em algum momento, as palavras "vingança é por este meio" foram gravadas no barril.Isso anteriormente pertencia a Micah Bell, mas ele não precisará mais.Essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e revólver explosivo.Em breve.', 7, 0.373, 92, 42.00, 82.00, 70.00, 55.00),
(45, 'Pistola da meia -noite','A pistola da meia -noite é uma arma na classe Pistols apresentada no modo de história de Red Dead Redemption 2. O design da pistola da meia -noite é baseado em uma pistola de Mauser C96 da vida real.A versão do jogo da arma é fabricada por Mühlberg.Esta arma não pode ser personalizada.A pistola da meia -noite só pode ser obtida no modo de história do RDR2 como uma recompensa de bônus.Ele fica disponível depois de concluir a missão o mais nobre dos homens e uma mulher (pistoleiros) no modo de história.Encontrado ao lado do corpo de Billy, meia -noite após seu duelo na missão de pistolas correspondente.Se você não pegar, não poderá adquiri -lo mais tarde.Uma pistola de Mauser rara, esta arma apresenta gravuras banhadas a ouro e uma aderência de madeira preta.Anteriormente de propriedade do Gunslinger Billy Midnight, derrotado em um duelo em um trem que sai de Rhodes, essa arma tem uma capacidade de munição de dez rodadas e pode usar munição regular, de alta velocidade, ponto dividido, expressar e explosivo.Em breve.', 3, 0.922, 96, 36.00, 80.00, 75.00, 67.00),
(46, 'Revolver da Marinha','O Revolver da Marinha é uma arma na classe Revolvers apresentada exclusivamente em Red Dead Online, adicionado ao jogo como parte da atualização de 1.15 Moonshiners em 13 de dezembro de 2019. O design do revólver da Marinha é baseado em um revólver da Marinha da Marinha da Vida Real 1851.Esta arma pode ser personalizada em qualquer um dos armeiros.Esta arma também aparece no GTA online.O revólver da Marinha pode ser comprado em Red Dead on -line em qualquer armeiro ou no catálogo de mão, por um preço de US $ 275,00 ou 11 barras de ouro.É baseado no famoso revólver da Marinha Colt de 1851.Veja isso .36 Revolver de ação única de calibre capaz de enviar uma bola de chumbo quente a uma velocidade surpreendente de 1.000 pés por segundo.Não existe nenhum agente de mamíferos nem receita capaz de superar sua eficácia mortal, e incentivamos você a provar o contrário.Em breve.Em breve.', 1, 0.297, 96, 52.00, 72.00, 50.00, 72.00),
(47, 'Otis Miller''s Revolver','O revólver de Otis Miller é uma arma na classe dos revólveres apresentada no modo Story of Red Dead Redemption 2. O design do revólver do Otis Miller é baseado em um revólver de Smith & Wesson Modelo 3 da Vida Real.A versão do jogo da arma é fabricada pela Hutton & Baird.Esta arma não pode ser personalizada.O revólver do Otis Miller só pode ser obtido no modo de história do RDR2 como uma recompensa de bônus.Ele fica disponível após a conclusão do epílogo da missão - parte 1 no modo de história.Um raro revólver Schofield feito de ouro e marfim, e adornado com gravuras personalizadas.Encontrado dentro de uma caverna em Cholla Springs, essa arma parece ter sido de propriedade do famoso pistoleiro Otis Miller.Essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e revólver explosivo.Em breve.', 7, 0.37, 91, 46.00, 70.00, 64.00, 75.00),
(48, 'Espingarda de ação da bomba','A espingarda de ação da bomba é uma arma na aula de espingardas apresentada em Red Dead Redemption 2 e Red Dead Online.O design da espingarda de ação da bomba é baseada em uma espingarda de Modelo 1897 da Vida Real Winchester.A versão do jogo da arma é fabricada por Lancaster.Esta arma pode ser personalizada em qualquer um dos armeiros.Esta arma também aparece em Grand Theft Auto VI, Grand Theft Auto V, Grand Theft Auto IV, GTA San Andreas, GTA Vice City e Grand Theft Auto III.A espingarda de ação da bomba pode ser comprada em Red Dead online em qualquer armeiro ou no catálogo de mão, por um preço de US $ 266,40 ou 11 barras de ouro.É desbloqueado para compra depois de atingir o Rank 5 em Red Dead Online.A espingarda de ação da bomba no RDR2 pode ser encontrada durante o assalto em casa Chez Porter (Grizzlies West, Ambarino), no topo da escada no quarto principal, ou pode ser comprado por um preço de US $ 148,00.Fica disponível após concluir a missão que derrama o óleo - III e IV no modo de história.A espingarda de bomba de lancaster de alta potência tem uma grande capacidade de munição e recursos rápidos de recarregar.Apesar da precisão média, essa arma se manterá verdadeira se você se encontrar por Besta Wild Beast ou Man em combate próximo.Essa arma tem uma capacidade de munição de cinco rodadas e pode usar uma munição regular de buckshot, buckshot incendiária, lesma e espingarda de lesma explosiva.Para o homem que tem mais língua do que sentido, o mero som da espingarda de ação da bomba de Lancaster carregando uma concha na câmara deve fazê-lo fechar a boca rapidamente.Achamos que o novo design de Lancaster torna esta a melhor espingarda de ação de bomba disponível hoje no mercado.Em breve.', 8, 0.288, 85, 61.00, 47.00, 60.00, 37.00),
(49, 'Rifle raro rolante','O rifle raro rolante é uma arma na classe Rifles Sniper apresentada no modo de história de Red Dead Redemption 2. O design do rifle raro rolante é baseado em um rifle de bloco de rolamento Remington da vida real.A versão do jogo da arma é fabricada por Litchfield.Esta arma não pode ser personalizada.O rifle raro rolante só pode ser obtido no modo de história RDR2 como uma recompensa de bônus.Ele fica disponível depois de concluir os mágicos da missão para o esporte no modo de história.Esta arma é lançada pelo atirador atirando do celeiro no final de "Magicians for Sport" (Capítulo 3).Se você não pegar, não poderá adquiri -lo mais tarde.Um rifle raro rolante feito de madeira clara e aço enegrecido, adornado com esculturas.Anteriormente pertencente a um caçador de recompensas depois de Josiah Trelawny, e encontrado em um celeiro perto de Braithwaite Manor, essa arma é uma arma única e pode usar uma munição de rifle expresso e explosiva.Em breve.', 5, 0.681, 99, 85.00, 27.00, 38.00, 85.00),
(50, 'Espingarda rara','A espingarda rara é uma arma na aula de espingardas apresentada em Red Dead Redemption 2 e Red Dead Online.O design da espingarda rara é baseada em uma espingarda de martelo do Modelo 1878 da vida real.A versão do jogo da arma é fabricada pela D.D.Packenbush.Esta arma não pode ser personalizada.A espingarda rara pode ser comprada em Red Dead online em qualquer armeiro ou no catálogo de mão, por um preço de US $ 258,00 ou 11 barras de ouro.A espingarda rara só pode ser obtida no modo de história do RDR2 como uma recompensa de bônus.No modo de história, a arma é jogada por um personagem especial chamado "The Hermit" quando você o mata.Se você não pegar, não poderá adquiri -lo mais tarde.Uma espingarda rara de cano duplo com manchas de latão desbotado e adornado com esculturas.Anteriormente, de propriedade e acalentado por um eremita solitária que vive em solidão entre as árvores e a vida selvagem de Roanoke Ridge.Esta arma tem uma capacidade de munição de duas rodadas e pode usar uma batida regular, uma munição de espingarda de lesma e slug explosiva.A espingarda rara é D.D.A variação lindamente gravada de Packenbush do poderoso longarm de barreiro duplo.Ostentando um acabamento de latão desbotado de estilo antigo e um estoque artisticamente adornado.Em breve.', 4, 0.172, 58, 65.00, 60.00, 45.00, 30.00),
(51, 'Repetindo espingarda','A espingarda repetida é uma arma na aula de espingardas apresentada em Red Dead Redemption 2 e Red Dead Online.O design da espingarda repetida é baseada em um modelo de Winchester da vida real 1887. A versão do jogo da arma é fabricada por Lancaster.Esta arma pode ser personalizada em qualquer um dos armeiros.A espingarda repetida pode ser comprada em Red Dead on -line em qualquer armeiro ou no catálogo portátil, por um preço de US $ 434,40 ou 18 barras de ouro.É desbloqueado para compra depois de atingir o Rank 11 em Red Dead Online.A espingarda repetida pode ser comprada no modo de história do RDR2 no Gunsmith por um preço de US $ 185,00.Ele fica disponível após concluir o horário de visita da missão no modo de história.A espingarda de repetição de Lancaster é uma arma completa que usa o mesmo sistema de ação de alavanca comumente encontrado na repetição de rifles.A grande capacidade de munição dá ao atirador o luxo de precisão, mantendo o poder ideal para encontros de perto.Essa arma tem uma capacidade de munição de seis rodadas e pode usar uma fusão regular de buckshot, buckshot incendiária, lesma e munição de espingarda de lesma explosiva.Uma maravilha de poder incomparável que essa espingarda repetida de Lancaster é reconhecida nacionalmente como o atirador mais forte do mercado.Você mal sentirá em suas mãos até que ele se afaste e, então, Senhor Todo -Poderoso, você fará orações a Deus primeiro e Lancaster logo depois.Disparar esta arma 10.000 vezes e veja.Em breve.', 5, 0.559, 72, 61.00, 50.00, 63.00, 34.00),
(52, 'Rifle de bloco de rolamento','O rifle de bloco rolante é uma arma na aula de rifles de sniper apresentada em Red Dead Redemption 2 e Red Dead Online.O design do rifle de bloco rolante é baseado em um rifle de bloco de rolamento Remington da vida real.A versão do jogo da arma é fabricada por Litchfield.Esta arma pode ser personalizada em qualquer um dos armeiros.O rifle de bloco rolante pode ser comprado em Red Dead on -line em qualquer armeiro ou no catálogo de mão, por um preço de US $ 411,00 ou 17 barras de ouro.Ele é desbloqueado para compra depois de atingir o Rank 13 em Red Dead Online.O rifle do bloco de rolamento pode ser comprado no modo RDR2 Story no Gunsmith por um preço de US $ 187,00.Ele fica disponível depois de concluir a missão as ovelhas e as cabras no modo de história.Projetado para caçar bestas grandes, o bloco de rolamento do Litchfield é um poderoso rifle de escopo longo, projetado para combate de longo alcance.Com múltiplos miras telescópicas disponíveis em diferentes níveis de zoom, um atirador de elite pode eliminar um alvo de longe e obter o elemento de surpresa.Esta arma é uma arma de tiro único e pode usar munição regular, de alta velocidade, ponto dividido, expresso e rifle explosivo.Você gosta de atirar elaria?Para aqueles que acreditam que o combate de perto é para a imprudente e de fato uma vida curta, então o rifle do bloco de rolamento de Litchfield é uma maravilha de se ver.É um homem corajoso que atira de longe.É um covarde que deixa cair um homem de apenas metros de distância.Em breve.', 3, 0.47, 74, 85.00, 27.00, 38.00, 85.00),
(53, 'Espingarda serrada','A espingarda serrada é uma arma na aula de espingardas apresentada em Red Dead Redemption 2 e Red Dead Online.O design da espingarda serrada é baseada em uma espingarda do Modelo de Modelo 1883 da vida real 1883.A versão do jogo da arma é fabricada pela Peeters & Janssens.Esta arma pode ser personalizada em qualquer um dos armeiros.Esta arma também aparece em Grand Theft Auto V, Grand Theft Auto IV e GTA San Andreas.A espingarda serrada pode ser comprada em Red Dead on-line em qualquer armeiro ou no catálogo portátil, por um preço de US $ 111,00 ou 5 barras de ouro.É desbloqueado para compra depois de atingir o Rank 19 em Red Dead Online.A espingarda serrada pode ser comprada no modo RDR2 Story no Gunsmith por um preço de US $ 85,00.Ele fica disponível após a conclusão da missão Enter, perseguida por uma memória no modo de história.O Peeters & Janssens serraram é uma espingarda versátil que pode ser usada facilmente com uma mão ou dupla empunhada com grande efeito.Ástuos e mortais, mas amplamente imprecisos, essa arma é ideal para um quarto de combate próximo a pé ou a cavalo.Esta arma tem uma capacidade de munição de duas rodadas e pode usar uma batida regular, uma munição de espingarda de lesma e slug explosiva.Se você está carregando algo em uma mão, como uma lanterna ou um animal pequeno, considere usar uma espingarda serrada que leva um soco muito maior de perto do que outras armas de uma mão.Uma espingarda leve que é fácil de usar e ocultar, como muitas situações nos tempos modernos exigem.A segurança e a durabilidade e, acima de tudo, a penetração superior desta espingarda fina não pode ser correspondida.Armas: espingarda serrada', 7, 0.917, 67, 65.00, 60.00, 50.00, 25.00),
(54, 'Revolver Schofield','O Revolver Schofield é uma arma na classe Revolver, apresentada em Red Dead Redemption 2 e Red Dead Online.O design do revólver Schofield é baseado em um revólver da vida real Smith & Wesson Modelo 3 "Schofield".A versão do jogo da arma é fabricada pela Hutton & Baird.Esta arma pode ser personalizada em qualquer um dos armeiros.O Revolver Schofield pode ser comprado em Red Dead online em qualquer armeiro ou no catálogo de mão, por um preço de US $ 192,00 ou 8 barras de ouro.É desbloqueado para compra depois de atingir o Rank 9 em Red Dead Online.O revólver Schofield no RDR2 pode ser encontrado durante o assalto ao médico de Valentine (The Heartlands, New Hanover), ou pode ser comprado por um preço de US $ 84,00.Fica disponível depois de concluir a missão abençoada são os mansos?no modo de história.O poderoso Hutton & Baird Schofield é um revólver preciso com altos danos, tornando -o a melhor escolha para qualquer pistoleiro sério.Apesar de uma taxa de disparo lenta e velocidade de recarga, quando comparada a outros revólveres, ainda pode ser empunhado com grande efeito.Essa arma tem uma capacidade de munição de seis rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e revólver explosivo.Todo homem prefere um revólver ou um companheiro que é estritamente de primeira classe em todos os aspectos.Embora a segunda ou a terceira classe muitas vezes possa ser suficiente em desespero ou no escuro da noite, não existe um modelo mais verdadeiro de revólver.Se você votar algo um incômodo, não há melhor maneira de despaci -lo.Em breve.', 8, 0.41, 98, 46.00, 70.00, 64.00, 70.00),
(55, 'Pistola semi -automática','A pistola semi -automática é uma arma na classe Pistols apresentada em Red Dead Redemption 2 e Red Dead Online.O design da pistola semi-automática é baseada em uma pistola Borchardt C-93 da vida real.A versão do jogo da arma é fabricada pela Peeters & Janssens.Esta arma pode ser personalizada em qualquer um dos armeiros.A pistola semi -automática pode ser comprada em Red Dead on -line em qualquer armeiro ou no catálogo portátil, por um preço de US $ 537,00 ou 22 barras de ouro.É desbloqueado para compra depois de atingir o Rank 22 em Red Dead Online.A pistola semi -automática pode ser comprada no modo de história RDR2 no Gunsmith por um preço de US $ 210,00.Ele fica disponível após concluir a missão as alegrias da civilização no modo de história.O novo Peeters & Janssens semi-automático causa menos danos do que o Revolver Sidemmms, mas compensa isso ao acabar com a necessidade de armar a arma, além de uma capacidade de munição expandida e recarregar a revista mais rápida.Essa arma tem uma capacidade de munição de oito rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e explosivo.Esta é estritamente uma arma de alta qualidade destinada a resolver situações de maneira rápida.Muito não se pode dizer sobre as qualidades de tiro desta pistola maravilhosa.Dire uma rodada e você verá - o recuo desta arma fina é uma prova de seu poder.Em breve.', 5, 0.655, 72, 33.00, 85.00, 80.00, 65.00),
(56, 'Espingarda semi-automática','A espingarda semi-automática é uma arma na aula de espingardas apresentada em Red Dead Redemption 2 e Red Dead Online.O design da espingarda semi-automática é baseada em uma espingarda Auto-5 da vida real.A versão do jogo da arma é fabricada por Brun et Fabre.Esta arma pode ser personalizada em qualquer um dos armeiros.A espingarda semi-automática pode ser comprada em Red Dead on-line em qualquer armeiro ou no catálogo portátil, por um preço de US $ 540,00 ou 22 barras de ouro.É desbloqueado para compra depois de atingir o Rank 42 em Red Dead Online.A espingarda semi-automática no RDR2 pode ser encontrada durante o assalto em casa de Watson, no porão (Big Valley, West Elizabeth), ou pode ser comprado por um preço de US $ 225,00.Ele fica disponível depois de concluir a missão uma bela noite de deboche no modo de história.O semi-automático de Brun et fabre embala o poder e a velocidade em uma espingarda.Apresentando uma forte taxa de incêndio, recarga rápida e um bom tamanho de revista, esta espingarda é perfeita para combate de curto alcance contra vários alvos.Essa arma tem uma capacidade de munição de cinco rodadas e pode usar uma munição regular de buckshot, buckshot incendiária, lesma e espingarda de lesma explosiva.Penetração inigualável repetidamente.A espingarda semi-automática de Brun et Fabre é a nota mais alta, a espingarda semi-automática mais perfeita e com preços mais perfeitos feita no mundo.Uma das armas de fogo sofisticadas mais atraentes do mercado.Em breve.', 2, 0.146, 56, 57.00, 55.00, 56.00, 40.00),
(57, 'Rifle Springfield','O rifle de Springfield é uma arma na aula de rifles apresentada em Red Dead Redemption 2 e Red Dead Online.O design do rifle de Springfield é baseado em uma carabina "Trapdoor" da Springfield Model 1873 da vida real.A versão do jogo da arma é fabricada por Lancaster.Esta arma pode ser personalizada em qualquer um dos armeiros.O rifle de Springfield pode ser comprado em Red Dead on -line em qualquer armeiro ou do catálogo de mão, por um preço de US $ 156,00 ou 7 barras de ouro.É desbloqueado para compra depois de atingir o Rank 38 em Red Dead Online.O rifle de Springfield pode ser comprado no modo RDR2 Story no Gunsmith por um preço de US $ 120,00.Ele fica disponível após concluir a missão que o leste vinculada no modo de história.Favorito militar, o Lancaster Springfield é uma poderosa arma de carregamento de culatra, projetada para combate de médio a longo prazo.A alta precisão torna essa arma eficaz contra grandes mamíferos, mas a taxa de disparo lenta pode ser um problema quando preso em quartos próximos.Esta arma é uma arma de tiro único e pode usar munição regular, de alta velocidade, ponto dividido, expresso e rifle explosivo.O rifle que modernizou o poder de fogo é o Lancaster Springfield, o rifle perfeito de carregamento de culatra.Passe pelo menos seis meses e pratique o tiroteio -alvo todos os dias e garantimos que você se tornará o objetivo.Armas: Rifle Springfield', 8, 0.606, 93, 80.00, 30.00, 43.00, 78.00),
(58, 'Rifle Varmint','O rifle Varmint é uma arma na aula de rifles apresentada em Red Dead Redemption 2 e Red Dead Online.O design do rifle Varmint é baseado em um modelo de Winchester da vida real 1890. A versão do jogo da arma é fabricada por Lancaster.Esta arma pode ser personalizada em qualquer um dos armeiros.O rifle Varmint pode ser comprado em Red Dead online em qualquer armeiro ou no catálogo portátil, por um preço de US $ 72,00 ou 3 barras de ouro.É desbloqueado para compra depois de atingir o Rank 8 em Red Dead Online.O rifle Varmint pode ser comprado no modo de história do RDR2 no Gunsmith por um preço de US $ 72,00.Ele fica disponível após concluir a missão que o leste vinculada no modo de história.O rifle Varmint, Lancaster Varmint, foi projetado para caçar pequenos mamíferos e pássaros grandes, usando um tipo especial de munição de baixo calibre com danos reduzidos.No entanto, a grande capacidade de munição e a taxa rápida de incêndio fazem desta uma arma eficaz contra grandes grupos de inimigos.Essa arma tem uma capacidade de munição de quatorze rodadas e só pode usar munição de calibre .22.É absolutamente garantido ser a melhor marca desse rifle de estilo do mercado.Atire uma vez e você verá que ele derruba Varmints com uma esplêndida hallop inigualável por outros rifles de baixo calibre.Um rifle de caça que toda a família pode desfrutar.Em breve.', 7, 0.444, 65, 42.00, 65.00, 68.00, 76.00),
(59, 'Pistola vulcânica','A pistola vulcânica é uma arma na classe Pistols apresentada em Red Dead Redemption 2 e Red Dead Online.O design da pistola vulcânica é baseada em um Smith da vida real e na pistola vulcânica Wesson 1855.A versão do jogo da arma é fabricada pela Hutton & Baird.Esta arma pode ser personalizada em qualquer um dos armeiros.A pistola vulcânica pode ser comprada em Red Dead online em qualquer armeiro ou no catálogo de mão, por um preço de US $ 270,00 ou 11 barras de ouro.É desbloqueado para compra depois de atingir o Rank 21 em Red Dead Online.A pistola vulcânica pode ser comprada no modo de história RDR2 no Gunsmith por um preço de US $ 150,00.Ele fica disponível após concluir a missão que o leste vinculada no modo de história.A pistola vulcânica Hutton & Baird combina a potência de parada de um rifle repetido com a portabilidade de uma arma.Embora a precisão seja boa, a taxa de disparo lenta e a velocidade de recarga significam que é melhor atingir seu alvo com o primeiro tiro.Essa arma tem uma capacidade de munição de oito rodadas e pode usar munição regular, de alta velocidade, ponto de divisão, expresso e explosivo.Esta pistola é a melhor criação da Hutton & Baird - direta da fábrica por meio do nosso armazém.Aponte na direção que você pretende, grite um palavrão inesquecível e puxe o gatilho da pistola vulcânica Hutton & Baird.Armas: pistola vulcânica', 2, 0.455, 96, 57.00, 50.00, 60.00, 72.00);

insert into arma_melee
(nome, descricao, peso, preco, durabilidadeMaxima, danoPorAtaque, nivelAfiacao)
values
(60, 'Faca de chifre','A faca de chifre é uma arma na classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.A faca de chifre no RDR2 só pode ser apanhada ao redor do mapa, é encontrada em um urso morto, a uma curta distância do noroeste do pendurado Ranch (Big Valley, West Elizabeth).Não pode ser comprado de outra forma.Uma faca rara, com uma alça fabricada a partir do chifre de um veado e parte da lâmina tirada perto do guarda cruzado.Esta arma foi retirada da cena de uma briga entre um grande urso e um caçador, que ocorreu perto da fazenda de cães pendurados em Big Valley.Nenhum dos lados ganhou.Em breve.', 4, 0.697, 51, 50.00, 8),
(61, 'Machete Eagle','O Machete Águila é uma arma na aula de armas corpo a corpo, destaque exclusivamente em Red Dead Online, adicionado ao jogo como parte da atualização de 1.11 Frontier Pursuits em 10 de setembro de 2019. Esta arma não pode ser personalizada.O facão Águila pode ser comprado em Red Dead online na Madame Nazar por um preço de US $ 150,00 ou 6 barras de ouro.Esta arma é um item exclusivo para jogadores on -line da Red Dead que assumem a função de colecionador.Esta arma é desbloqueada quando você atinge o coletor da classificação 5. Um facão clássico reestyled para o uso de colecionadores aventureiros e beligerantes.Esta arma é um item exclusivo para jogadores que assumem o papel de especialista em colecionadores como parte das atividades de fronteira.Em breve.Em breve.', 5, 0.871, 71, 55.00, 9),
(62, 'Espada de pirata quebrada','A Broken Pirate Sword é uma arma na classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.A espada de pirata quebrada no RDR2 só pode ser apanhada ao redor do mapa, é encontrada em um barco destruído nas pequenas ilhas diretamente ao sul da ponte sul em Saint Denis (Bayou Nwa, Lemoyne).Não pode ser comprado de outra forma.Um cutelo pirata antigo e raro, com uma longa lâmina e protetor de mão dourado decorativo.Esta relíquia foi encontrada alojada dentro de um barco abandonado, correndo à deriva nos pântanos em torno de Saint Denis.Com um alcance mais longo do que a maioria das armas corpo a corpo, isso ainda é uma arma de combate prática, apesar de sua idade.Em breve.', 8, 0.86, 98, 55.00, 6),
(63, 'Faca de Guerra Civil','A faca da Guerra Civil é uma arma na classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.A faca da Guerra Civil no RDR2 só pode ser apanhada ao redor do mapa, é encontrada em uma caixa no porão de Fort Brennand (Roanoke Ridge, New Hanover), um forte sudoeste de Van Horn.Não pode ser comprado de outra forma.Uma faca de Bowie velha com uma lâmina sólida, alça de madeira gasta e protetora de mão grande em forma de D para proteção.Esta arma era comumente usada por soldados da Guerra Civil e é coberta de ferrugem.Foi encontrado em uma sala de armazenamento embaixo do arruinado Fort Brennand em Roanoke Ridge, New Hanover.Vá para a fortaleza de guerra civil arruinada mostrada no mapa, está localizada a sudoeste do posto de comércio de van Horn.Quando chegar ao forte, entre no prédio e desça a escada.No porão, você encontrará a faca da Guerra Civil e um chapéu de guerra civil perto do peito.Em breve.', 2, 0.358, 69, 50.00, 7),
(64, 'Cleaver','The Cleaver é uma arma nas armas jogadas, aula de armas corpo a corpo apresentada em Red Dead Redemption 2 e Red Dead Online.Esta arma não pode ser personalizada.Esta arma também aparece no GTA Vice City.O Cleaver pode ser adquirido em Red Dead online a qualquer cerca por um preço de US $ 8,00.É desbloqueado para compra depois de atingir o Rank 15 em Red Dead Online.O Cleaver pode ser comprado no modo RDR2 Story na cerca por um preço de US $ 8,00.Fica disponível após concluir a missão, querido tio Tácito no modo de história.Um machado de lâmina larga com uma alça de madeira curta, essa ferramenta de caça e cozinha é geralmente usada para preparar carcaças de animais e cortar carne grossa, cartilagem e osso.Como você pode imaginar, essas propriedades também contribuem para uma arma de combate eficaz e também pode ser jogada.Em breve.', 2, 0.29, 73, 60.00, 6),
(65, 'Hatchet duplo','O machado duplo é uma arma nas armas jogadas, a classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.O hatchet duplo no RDR2 só pode ser recolhido ao redor do mapa, é encontrado em um tronco de árvore a noroeste da estação Wallace (Big Valley, West Elizabeth).Não pode ser comprado de outra forma.Uma machadinha rara, com uma cabeça de lâmina dupla: um lado nítido para cortar e cortar;e um lado opaco para dividir madeira.Esta arma corpo a corpo foi encontrada em um toco de árvore perto da estação de Wallace, em Big Valley, e parece ser bastante novo.Este machado também pode ser jogado.Em breve.', 4, 0.168, 73, 60.00, 3),
(66, 'Luar inflamável','O luar inflamável é uma arma nas armas jogadas, a classe de armas corpo a corpo destacadas exclusivamente em Red Dead Online, adicionado ao jogo como parte da atualização de 1.15 Moonshiners em 13 de dezembro de 2019. Esta arma não pode ser personalizada.O luar inflamável pode ser comprado em Red Dead on -line em qualquer cerca por um preço de US $ 20,00 ou 1 bar de ouro.Esta arma é um item exclusivo para jogadores on -line do Red Dead que assumem o papel de Moonshiner.Requer 2 tokens de função + raça de função de Moonshiner 5. É descrito como "álcool altamente potente que pode ser derramado e incendiado".O luar inflamável funciona essencialmente como o Jerry Can em Gta V, derramando uma trilha de luar e depois disparando para acender a trilha e objetos próximos em chamas.O luar inflamável pode ser adquirido na Moonshiner Store por US $ 20, depois de atingir a função de Moonshiner Rank 5 e obter 2 tokens de função.Em breve.', 2, 0.514, 69, 20.00, 6),
(67, 'Martelo','O Hammer é uma arma na aula de armas corpo a corpo destacada exclusivamente em Red Dead Online, adicionado ao jogo como parte da atualização de atividades de 1,11 Frontier em 10 de setembro de 2019. Esta arma não pode ser personalizada.Esta arma também aparece em Grand Theft Auto V e GTA Vice City.O martelo pode ser comprado em Red Dead on -line a qualquer cerca por um preço de US $ 75,00 ou 3 barras de ouro.Esta arma é um item exclusivo para jogadores on -line da Red Dead que assumem o cargo de trader.Esta arma é desbloqueada quando você chega ao Trader Rank 1. Um martelo clássico contribui para uma arma corpo a corpo contundente.Esta arma é um item exclusivo para jogadores que assumem a função de especialista em comerciantes como parte do Kit Novice.Em breve.Em breve.', 7, 0.87, 50, 40.00, 6),
(68, 'Machadinha','O hatchet é uma arma nas armas arremessadas, a classe de armas corpo a corpo apresentada em Red Dead Redemption 2 e Red Dead Online.Esta arma não pode ser personalizada.Esta arma também aparece no Grand Theft Auto V. O hatchet pode ser comprado em Red Dead online a qualquer cerca por um preço de US $ 4,25.É desbloqueado para compra depois de atingir o Rank 28 em Red Dead Online.O hatchet pode ser comprado no modo RDR2 Story na cerca por um preço de US $ 4,25.Fica disponível após concluir a missão, querido tio Tácito no modo de história.Um machado de mão básico, com uma lâmina de aço com entalhes e uma longa alça de madeira.Projetado para cortar madeira, esta poderosa arma de uma mão pode ser girada para causar uma grande quantidade de danos a um oponente.Em uma pitada, ele também pode ser jogado em um alvo para derrubá -los à distância.Em breve.', 5, 0.705, 81, 60.00, 5),
(69, 'Hatchet Hewing','O machado hewing é uma arma nas armas jogadas, a classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.O machado hewing no RDR2 só pode ser apanhado ao redor do mapa, é encontrado em um toco de árvore na costa sul de Moonstone Pond (Grizzlies East, Ambarino).Não pode ser comprado de outra forma.Este machado antigo e gasto tem uma borda plana ao longo de um lado da lâmina e foi projetada para Hewing, o processo de conversão de troncos em madeira.Esta arma corpo a corpo foi encontrada em um toco de árvore perto de Moonstone Pond, no Grizzlies, ao lado de uma cabana abandonada.Este machado também pode ser jogado.Registrado no toco da árvore à direita, caminhe até o toco e você verá um aviso para pegar o machado hewing.A casa que tem a árvore através do teto também possui frutas.Em breve.', 3, 0.753, 84, 60.00, 4),
(70, 'Hatchet de Hunter','O hatchet Hunter é uma arma nas armas jogadas, aula de armas corpo a corpo apresentada na Red Dead Redemption 2 e Red Dead Online.Esta arma não pode ser personalizada.O hatchet de Hunter pode ser comprado em Red Dead on -line em qualquer cerca por um preço de US $ 5,00.O hatchet de Hunter no RDR2 só pode ser recolhido ao redor do mapa, é encontrado em um tronco de árvore diretamente ao sul de Window Rock (Grizzlies West, Ambarino).Não pode ser comprado de outra forma.Um machado raro, com um bit longo de machado barbudo que permite maior controle ao planejar ou fazer a barbear madeira.No modo de história, esta arma corpo a corpo é encontrada em um toco de árvore perto de Window Rock nos Grizzlies e parece ser bastante novo.Este machado também pode ser jogado.O hatchet de Hunter é uma arma brutal e afiada, construída para esconder a carne e os ossos.Agora é transportado em Red Dead online por cercas locais em Saint Denis, Emerald Ranch, Van Horn e Rhodes.Em breve.', 8, 0.97, 52, 60.00, 10),
(71, 'Faca de caça','A faca de caça é uma arma na aula de armas corpo a corpo apresentada em Red Dead Redemption 2 e Red Dead Online.Esta arma pode ser personalizada em qualquer um dos armeiros.Esta arma também aparece em Grand Theft Auto VI, Grand Theft Auto V, Grand Theft Auto IV, GTA San Andreas e GTA Vice City.Ele fica disponível depois de concluir os bandidos da missão do oeste no modo de história.Disponível desde o início do jogo.Uma faca de Bowie para todos os fins com uma lâmina nítida de ponto de clipe, guard de aço e alça de madeira resistente.Projetado para combate, esta arma pode dar a vantagem a qualquer luta corpo a corpo curta ou ser usada para quedas silenciosas.Para os caçadores, esta também é a arma perfeita para matar e esfolar animais.Lembre -se: não há regras em uma luta de facas.Em breve.', 1, 0.521, 91, 50.00, 1),
(72, 'Faca Jawbone','A faca da mandíbula é uma arma na aula de armas corpo a corpo apresentada em Red Dead Redemption 2 e Red Dead Online.Esta arma não pode ser personalizada.A faca da mandíbula pode ser comprada em Red Dead on -line a qualquer cerca por um preço de US $ 105,00 ou 5 barras de ouro.A faca da mandíbula só pode ser obtida no modo de história do RDR2 como uma recompensa de bônus.Ele fica disponível após concluir a missão um teste de fé (ossos de dinossauros colecionáveis) no modo de história.Uma faca rara criada, feita com um grande pedaço de pederneira como uma lâmina e o maxilar de um coiote como alça.Uma recompensa por coletar ossos de dinossauros para Deborah Macguiness, um paleontologista amador localizado em Firwood Rise, Cumberland Forest.Em breve.', 2, 0.993, 78, 50.00, 10),
(73, 'Faca de John','A faca de John é uma arma na classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.Ele fica disponível após a conclusão do epílogo da missão - parte 1 no modo de história.De propriedade de John Marston, esta faca de caça robusta combina uma lâmina mortal com uma alça de madeira estreita.Útil para derrubar silenciosamente um alvo sem alertar seus amigos, esfolar sua presa após um longo dia de caça à região selvagem ou lutando contra lobos em uma montanha nevada.Em breve.', 4, 0.722, 57, 50.00, 8),
(74, 'Facão','O facão é uma arma na aula de armas corpo a corpo apresentada em Red Dead Redemption 2 e Red Dead Online.Esta arma não pode ser personalizada.Esta arma também aparece em Grand Theft Auto V e GTA Vice City.O facão pode ser comprado em Red Dead on -line em qualquer cerca por um preço de US $ 40,00 ou 2 barras de ouro.É desbloqueado para compra depois de atingir o Rank 32 em Red Dead Online.O facão pode ser comprado no modo RDR2 Story na cerca por um preço de US $ 10,00.Fica disponível após concluir a missão, querido tio Tácito no modo de história.Com uma lâmina ampla afiada, o facão é projetado para colheita de cana -de -açúcar ou limpeza através da vegetação rasteira da floresta.No entanto, isso não impede que seja uma arma corpo a corpo eficaz, com um alcance mais longo do que a maioria.Um hack forte com esta arma derrubará qualquer alvo de maneira rápida e silenciosa.Em breve.', 4, 0.37, 82, 55.00, 8),
(75, 'Dagger ornamentada','A adaga ornamentada é uma arma na classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.Uma punhal decorativa rara, com uma lâmina prateada em relevo com designs ornamentados e uma alça de estatueta de ouro.Esta arma anteriormente pertencia a um homem pálido estranho vestido de preto, descoberto à espreita entre os bastidores de São Denis.Em breve.', 1, 0.344, 55, 50.00, 7),
(76, 'Hatchet duplo enferrujado','O hatchet duplo enferrujado é uma arma nas armas jogadas, a classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.O hatchet duplo enferrujado no RDR2 só pode ser recolhido ao redor do mapa, é encontrado em um toco de árvore em Annesburg (Roanoke Ridge, New Hanover), a uma curta caminhada ao norte da instalação de mineração de carvão.Não pode ser comprado de outra forma.Uma machadinha rara, com uma cabeça de lâmina dupla enferrujada: um lado nítido para cortar e cortar;e um lado opaco para dividir madeira.Esta arma corpo a corpo foi encontrada em um toco de árvore perto da mina de Annesburg em Roanoke Ridge e foi usado pelos elementos ao longo do tempo.Este machado também pode ser jogado.Em breve.', 1, 0.651, 51, 60.00, 6),
(77, 'Hatchet de caçador enferrujado','O Hatchet Hunter Rusted é uma arma nas armas jogadas, a classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.O hatchet de caçador enferrujado no RDR2 só pode ser pego em torno do mapa, é encontrado em um toco de árvore do lado de fora de uma cabana, a meio caminho entre a corrida de O''Creagh e a piscina elástica (Grizzlies East, Ambarino).Não pode ser comprado de outra forma.Um machado raro, com um bit longo de machado barbudo que permite maior controle ao planejar ou fazer a barbear madeira.A arma corpo a corpo foi encontrada em um toco de árvore perto de três irmãs no Grizzlies e foi usado pelos elementos ao longo do tempo.Este machado também pode ser jogado.Em breve.', 1, 0.712, 91, 60.00, 4),
(78, 'Hatchet de pedra','O Hatchet de Pedra é uma arma nas armas jogadas, a classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.Esta arma também aparece no GTA online.O machado de pedra só pode ser obtido no modo de história do RDR2 como uma recompensa de bônus.Ele fica disponível após concluir o Capítulo 2 da Missão no modo de história.Disponível apenas para jogadores que completam a missão de Hunter de Bounty Related no GTA on -line e obtém 25 mortes corpo a corpo com o Hatchet de pedra no GTA on -line.Para desbloquear o machado de pedra em Red Dead Redemption 2, você deve seguir estas etapas: se você descobriu o hatchet de pedra ao concluir os empregos de recompensa de Maude no GTA on -line, encontre o cemitério indiano depois de concluir a primeira missão no capítulo 2em Red Dead Redemption 2. O machado de pedra está no centro deste lugar misterioso.Uma machadinha antiga e rara feita de uma grande lâmina de pedra, tiras de couro e penas.Esta arma corpo a corpo é encontrada em um cemitério nativo em Big Valley, West Elizabeth, e provavelmente foi usado como parte da cerimônia do enterro.Este machado também pode ser jogado.Este vídeo mostra onde encontrar o machado de pedra em Red Dead Redemption 2:', 2, 0.585, 69, 60.00, 10),
(79, 'Desarmado (punho)','Lutar com os punhos no Red Dead Redemption 2 pode ser útil quando a munição é escassa ou para evitar chamar a atenção indesejada.Também funciona bem quando são necessários métodos não letais, como roubo ou intimidação.Leve -se de perto e bata seus inimigos na submissão ou incorpore uma arma corpo a corpo com lâmina se você estiver fora de sangue.', 6, 0.828, 66, 30.00, 6),
(80, 'Viking Hatchet','O machado viking é uma arma nas armas jogadas, a classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.O machado viking no RDR2 só pode ser recolhido ao redor do mapa, é encontrado na antiga tumba, a uma curta distância do nordeste de Beaver Hollow (Roanoke Ridge, New Hanover).Não pode ser comprado de outra forma.Um raro machado antigo, gravado por todo o lado com padrões nórdicos e ligado a couro.Esta arma corpo a corpo foi encontrada em um antigo altar de pedra na área de Roanoke Valley, em New Hanover, alojada em um crânio.Este machado também pode ser jogado.A localização da antiga tumba é o extremo noroeste de New Hanover, escondido no sul do vale de Roanoke.A localização exata da tumba antiga mostra um símbolo de estrela no mapa.Entrada antiga da tumba: o machado viking está enterrado no crânio de um guerreiro há muito perdido cujo esqueleto permanece em um altar.Em breve.', 8, 0.771, 100, 60.00, 7),
(81, 'Faca de lâmina larga','A faca de lâmina larga é uma arma na classe de armas corpo a corpo apresentada no modo de história de Red Dead Redemption 2. Esta arma não pode ser personalizada.A faca de lâmina larga no RDR2 só pode ser apanhada ao redor do mapa, é encontrada em um cadáver profundamente na mina dos sonhos de Beryl, diretamente a oeste de Mount Shann (Big Valley, West Elizabeth).Pressione o êmbolo na entrada para explodir as rochas no caminho.Não pode ser comprado de outra forma.Uma faca de caça rara, com uma lâmina larga de ponto de clipe e alça de madeira curvada.Esta faca foi encontrada saindo da parte de trás de um cadáver nas minas do sonho de Beryl, Big Valley.O proprietário anterior dessa arma se esforçou muito para impedir que seu crime fosse descoberto.Em breve.', 7, 0.616, 90, 50.00, 3),
(82, 'O machê','O Machete Zavala é uma arma na aula de armas corpo a corpo, destaque exclusivamente em Red Dead Online, adicionado ao jogo como parte da atualização de 1.23 Halloween Pass em 20 de outubro de 2020. Esta arma não pode ser personalizada.O Machete Zavala pode ser comprado em Red Dead online em qualquer cerca por um preço.Esta arma é um item exclusivo em Red Dead Online, desbloqueado ao atingir a classificação 20 do Pass de Halloween 2020. O facão Zavala é um facão grande e nítido com uma alça ornamentada.', 4, 0.333, 67, 55.00, 2);